# Generated by OmopViewer 0.4.0
# Be careful editing this file

server <- function(input, output, session) {
  # download raw data -----
  output$download_raw <- shiny::downloadHandler(
    filename = "results.csv",
    content = function(file) {
      data |>
        omopgenerics::bind() |>
        omopgenerics::exportSummarisedResult(fileName = file)
    }
  )
  # update buttons ----
  updateButtons <- shiny::reactiveValues(
    summarise_omop_snapshot = FALSE,
    summarise_cohort_count = FALSE,
    summarise_cohort_attrition = FALSE,
    summarise_characteristics = FALSE,
    summarise_large_scale_characteristics = FALSE,
    incidence = FALSE,
    incidence_attrition = FALSE
  )
  
  # summarise_omop_snapshot -----
  ## update message if filter is changed
  shiny::observeEvent(input$summarise_omop_snapshot_cdm_name,
                      {
                        updateButtons$summarise_omop_snapshot <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_omop_snapshot_variable_name,
                      {
                        updateButtons$summarise_omop_snapshot <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$summarise_omop_snapshot, {
    if (updateButtons$summarise_omop_snapshot == TRUE) {
      output$update_message_summarise_omop_snapshot <- shiny::renderText("Filters have changed please consider to use the update content button!")
    } else {
      output$update_message_summarise_omop_snapshot <- shiny::renderText("")
    }
  })
  shiny::observeEvent(input$update_summarise_omop_snapshot, {
    updateButtons$summarise_omop_snapshot <- FALSE
  })
  
  ## get summarise_omop_snapshot data
  getSummariseOmopSnapshotTable <- shiny::reactive({
    data[["summarise_omop_snapshot"]]  |>
      OmopSketch::tableOmopSnapshot()
  })
  output$summarise_omop_snapshot_table <- gt::render_gt({
    getSummariseOmopSnapshotTable()
  })
  output$summarise_omop_snapshot_table_download <- shiny::downloadHandler(
    filename = paste0("table_snapshot.", input$summarise_omop_snapshot_table_format),
    content = function(file) {
      gt::gtsave(getSummariseOmopSnapshotTable(), file)
    }
  )
  # summarise_cohort_count -----
  ## update message if filter is changed
  shiny::observeEvent(input$summarise_cohort_count_cdm_name,
                      {
                        updateButtons$summarise_cohort_count <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_cohort_count_variable_name,
                      {
                        updateButtons$summarise_cohort_count <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_cohort_count_table_name,
                      {
                        updateButtons$summarise_cohort_count <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$summarise_cohort_count, {
    if (updateButtons$summarise_cohort_count == TRUE) {
      output$update_message_summarise_cohort_count <- shiny::renderText("Filters have changed please consider to use the update content button!")
    } else {
      output$update_message_summarise_cohort_count <- shiny::renderText("")
    }
  })
  shiny::observeEvent(input$update_summarise_cohort_count, {
    updateButtons$summarise_cohort_count <- FALSE
  })
  
  ## get summarise_cohort_count data
  getSummariseCohortCountData <- shiny::eventReactive(input$update_summarise_cohort_count, {
    data[["summarise_cohort_count"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_cohort_count_cdm_name,
        .data$variable_name %in% input$summarise_cohort_count_variable_name
      ) |>
      omopgenerics::filterSettings(.data$table_name %in% input$summarise_cohort_count_table_name)
  })
  getSummariseCohortCountTidy <- shiny::reactive({
    tidyDT(getSummariseCohortCountData(), input$summarise_cohort_count_tidy_columns, input$summarise_cohort_count_tidy_pivot_estimates)
  })
  output$summarise_cohort_count_tidy <- DT::renderDT({
    getSummariseCohortCountTidy()
  })
  output$summarise_cohort_count_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getSummariseCohortCountData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getSummariseCohortCountTable <- shiny::reactive({
    getSummariseCohortCountData() |>
      CohortCharacteristics::tableCohortCount(
        header = input$summarise_cohort_count_table_header,
        groupColumn = input$summarise_cohort_count_table_group_column,
        hide = input$summarise_cohort_count_table_hide
      )
  })
  output$summarise_cohort_count_table <- gt::render_gt({
    getSummariseCohortCountTable()
  })
  output$summarise_cohort_count_table_download <- shiny::downloadHandler(
    filename = paste0("table_count.", input$summarise_cohort_count_table_format),
    content = function(file) {
      gt::gtsave(getSummariseCohortCountTable(), file)
    }
  )
  getSummariseCohortCountPlot <- shiny::reactive({
    getSummariseCohortCountData() |>
      CohortCharacteristics::plotCohortCount(
        facet = input$summarise_cohort_count_plot_facet,
        colour = input$summarise_cohort_count_plot_colour
      )
  })
  output$summarise_cohort_count_plot <- shiny::renderUI({
    x <- getSummariseCohortCountPlot()
    renderInteractivePlot(x, input$summarise_cohort_count_plot_interactive)
  })
  output$summarise_cohort_count_plot_download <- shiny::downloadHandler(
    filename = "plot_count.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseCohortCountPlot(),
        width = as.numeric(input$summarise_cohort_count_plot_width),
        height = as.numeric(input$summarise_cohort_count_plot_height),
        units = input$summarise_cohort_count_plot_units,
        dpi = as.numeric(input$summarise_cohort_count_plot_dpi)
      )
    }
  )
  # summarise_cohort_attrition -----
  ## update message if filter is changed
  shiny::observeEvent(input$summarise_cohort_attrition_cdm_name,
                      {
                        updateButtons$summarise_cohort_attrition <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_cohort_attrition_variable_name,
                      {
                        updateButtons$summarise_cohort_attrition <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$summarise_cohort_attrition, {
    if (updateButtons$summarise_cohort_attrition == TRUE) {
      output$update_message_summarise_cohort_attrition <- shiny::renderText("Filters have changed please consider to use the update content button!")
    } else {
      output$update_message_summarise_cohort_attrition <- shiny::renderText("")
    }
  })
  shiny::observeEvent(input$update_summarise_cohort_attrition, {
    updateButtons$summarise_cohort_attrition <- FALSE
  })
  
  ## get summarise_cohort_attrition data
  getSummariseCohortAttritionData <- shiny::eventReactive(input$update_summarise_cohort_attrition, {
    data[["summarise_cohort_attrition"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_cohort_attrition_cdm_name,
        .data$variable_name %in% input$summarise_cohort_attrition_variable_name
      )
  })
  getSummariseCohortAttritionTidy <- shiny::reactive({
    tidyDT(getSummariseCohortAttritionData(), input$summarise_cohort_attrition_tidy_columns, input$summarise_cohort_attrition_tidy_pivot_estimates)
  })
  output$summarise_cohort_attrition_tidy <- DT::renderDT({
    getSummariseCohortAttritionTidy()
  })
  output$summarise_cohort_attrition_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getSummariseCohortAttritionData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getSummariseCohortAttritionTable <- shiny::reactive({
    getSummariseCohortAttritionData() |>
      CohortCharacteristics::tableCohortAttrition(
        header = input$summarise_cohort_attrition_table_header,
        groupColumn = input$summarise_cohort_attrition_table_group_column,
        hide = input$summarise_cohort_attrition_table_hide
      )
  })
  output$summarise_cohort_attrition_table <- gt::render_gt({
    getSummariseCohortAttritionTable()
  })
  output$summarise_cohort_attrition_table_download <- shiny::downloadHandler(
    filename = paste0("table_attrition.", input$summarise_cohort_attrition_table_format),
    content = function(file) {
      gt::gtsave(getSummariseCohortAttritionTable(), file)
    }
  )
  getSummariseCohortAttritionDiagram <- shiny::reactive({
    getSummariseCohortAttritionData() |>
      CohortCharacteristics::plotCohortAttrition(
        show = input$summarise_cohort_attrition_diagram_show
      )
  })
  output$summarise_cohort_attrition_diagram <- DiagrammeR::renderGrViz({
    getSummariseCohortAttritionDiagram()
  })
  output$summarise_cohort_attrition_diagram_download <- shiny::downloadHandler(
    filename = "attrition_diagram.png",
    content = function(file) {
      svg <- DiagrammeRsvg::export_svg(getSummariseCohortAttritionDiagram())
      rsvg::rsvg_png(charToRaw(svg), file, width = input$summarise_cohort_attrition_diagram_width)
    }
  )
  # summarise_characteristics -----
  ## update message if filter is changed
  shiny::observeEvent(input$summarise_characteristics_cdm_name,
                      {
                        updateButtons$summarise_characteristics <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_characteristics_cohort_name,
                      {
                        updateButtons$summarise_characteristics <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_characteristics_variable_name,
                      {
                        updateButtons$summarise_characteristics <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_characteristics_estimate_name,
                      {
                        updateButtons$summarise_characteristics <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$summarise_characteristics, {
    if (updateButtons$summarise_characteristics == TRUE) {
      output$update_message_summarise_characteristics <- shiny::renderText("Filters have changed please consider to use the update content button!")
    } else {
      output$update_message_summarise_characteristics <- shiny::renderText("")
    }
  })
  shiny::observeEvent(input$update_summarise_characteristics, {
    updateButtons$summarise_characteristics <- FALSE
  })
  
  ## get summarise_characteristics data
  getSummariseCharacteristicsData <- shiny::eventReactive(input$update_summarise_characteristics, {
    data[["summarise_characteristics"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_characteristics_cdm_name,
        .data$variable_name %in% input$summarise_characteristics_variable_name,
        .data$estimate_name %in% input$summarise_characteristics_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_characteristics_cohort_name)
  })
  getSummariseCharacteristicsTable <- shiny::reactive({
    getSummariseCharacteristicsData() |>
      dplyr::filter(
        !variable_name %in% c("Cohort start date", "Cohort end date", "Age", "Sex", "Prior observation", "Future observation", "Days in cohort")
      ) |>
      dplyr::mutate(
        variable_level = dplyr::if_else(variable_name == "Previous pregnancies", "-", variable_level),
        variable_name = factor(
          variable_name, 
          levels = c(
            "Number records", "Number subjects", "Maternal age", "Trimester", "Season", "Season yearly",
            "Ethnicity", "History of comorbidities", "Mental heatlh problems in the last year",
            "Covariates in the past 5 years", "Medications in the past year", 
            "Previous pregnancies"  
          )
        )
      ) |>
      dplyr::arrange(variable_name, variable_level) |>
      CohortCharacteristics::tableCharacteristics(
        header = input$summarise_characteristics_table_header,
        groupColumn = input$summarise_characteristics_table_group_column,
        hide = input$summarise_characteristics_table_hide
      )
  })
  output$summarise_characteristics_table <- gt::render_gt({
    getSummariseCharacteristicsTable()
  })
  output$summarise_characteristics_table_download <- shiny::downloadHandler(
    filename = paste0("table_characteristics.", input$summarise_characteristics_table_format),
    content = function(file) {
      gt::gtsave(getSummariseCharacteristicsTable(), file)
    }
  )
  getSummariseCharacteristicsPlot <- shiny::reactive({
    getSummariseCharacteristicsData() |>
      CohortCharacteristics::plotCharacteristics(
        plotType = input$summarise_characteristics_plot_plot_type,
        facet = input$summarise_characteristics_plot_facet,
        colour = input$summarise_characteristics_plot_colour
      )
  })
  output$summarise_characteristics_plot <- shiny::renderUI({
    x <- getSummariseCharacteristicsPlot()
    renderInteractivePlot(x, input$summarise_characteristics_plot_interactive)
  })
  output$summarise_characteristics_plot_download <- shiny::downloadHandler(
    filename = "plot_characteristics.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseCharacteristicsPlot(),
        width = as.numeric(input$summarise_characteristics_plot_width),
        height = as.numeric(input$summarise_characteristics_plot_height),
        units = input$summarise_characteristics_plot_units,
        dpi = as.numeric(input$summarise_characteristics_plot_dpi)
      )
    }
  )
  # summarise_large_scale_characteristics -----
  ## update message if filter is changed
  shiny::observeEvent(input$summarise_large_scale_characteristics_cdm_name,
                      {
                        updateButtons$summarise_large_scale_characteristics <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_large_scale_characteristics_cohort_name,
                      {
                        updateButtons$summarise_large_scale_characteristics <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_large_scale_characteristics_variable_level,
                      {
                        updateButtons$summarise_large_scale_characteristics <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_large_scale_characteristics_analysis,
                      {
                        updateButtons$summarise_large_scale_characteristics <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_large_scale_characteristics_table_name,
                      {
                        updateButtons$summarise_large_scale_characteristics <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_large_scale_characteristics_type,
                      {
                        updateButtons$summarise_large_scale_characteristics <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$summarise_large_scale_characteristics, {
    if (updateButtons$summarise_large_scale_characteristics == TRUE) {
      output$update_message_summarise_large_scale_characteristics <- shiny::renderText("Filters have changed please consider to use the update content button!")
    } else {
      output$update_message_summarise_large_scale_characteristics <- shiny::renderText("")
    }
  })
  shiny::observeEvent(input$update_summarise_large_scale_characteristics, {
    updateButtons$summarise_large_scale_characteristics <- FALSE
  })
  
  ## get summarise_large_scale_characteristics data
  getSummariseLargeScaleCharacteristicsData <- shiny::eventReactive(input$update_summarise_large_scale_characteristics, {
    data[["summarise_large_scale_characteristics"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_large_scale_characteristics_cdm_name,
        .data$variable_level %in% input$summarise_large_scale_characteristics_variable_level
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_large_scale_characteristics_cohort_name) |>
      omopgenerics::filterSettings(
        .data$analysis %in% input$summarise_large_scale_characteristics_analysis,
        .data$table_name %in% input$summarise_large_scale_characteristics_table_name,
        .data$type %in% input$summarise_large_scale_characteristics_type
      )
  })
  getSummariseLargeScaleCharacteristicsTableLsc <- shiny::reactive({
    if (identical(input$summarise_large_scale_characteristics_table_lsc_compare_by, "no compare")) {
      cb <- NULL
    } else {
      cb <- input$summarise_large_scale_characteristics_table_lsc_compare_by
    }
    if (identical(input$summarise_large_scale_characteristics_table_lsc_smd_reference, "no SMD")) {
      sr <- NULL
    } else {
      sr <- input$summarise_large_scale_characteristics_table_lsc_smd_reference
    }
    getSummariseLargeScaleCharacteristicsData() |>
      CohortCharacteristics::tableLargeScaleCharacteristics(
        compareBy = cb,
        hide = input$summarise_large_scale_characteristics_table_lsc_hide,
        smdReference = sr
      )
  })
  output$summarise_large_scale_characteristics_table_lsc <- reactable::renderReactable({
    getSummariseLargeScaleCharacteristicsTableLsc()
  })
  shiny::observeEvent(input$summarise_large_scale_characteristics_table_lsc_compare_by, {
    opts <- values[[paste0("summarise_large_scale_characteristics_", input$summarise_large_scale_characteristics_table_lsc_compare_by)]]
    opts <- c("no SMD", opts)
    shinyWidgets::updatePickerInput(
      inputId = "summarise_large_scale_characteristics_table_lsc_smd_reference",
      choices = opts,
      selected = "no SMD"
    )
  })
  output$summarise_large_scale_characteristics_table_lsc_download <- shiny::downloadHandler(
    filename = "smd_results.csv",
    content = function(file) {
      rt <- getSummariseLargeScaleCharacteristicsTableLsc()
      rt$x$tag$attribs$data |>
        unclass() |>
        jsonlite::fromJSON() |>
        dplyr::as_tibble() |>
        readr::write_csv(file)
    }
  )
  getSummariseLargeScaleCharacteristicsTableMostCommon <- shiny::reactive({
    getSummariseLargeScaleCharacteristicsData() |>
      CohortCharacteristics::tableTopLargeScaleCharacteristics(
        topConcepts = input$summarise_large_scale_characteristics_table_most_common_top_concepts,
        type = "gt"
      )
  })
  output$summarise_large_scale_characteristics_table_most_common <- gt::render_gt({
    getSummariseLargeScaleCharacteristicsTableMostCommon()
  })
  output$summarise_large_scale_characteristics_table_most_common_download <- shiny::downloadHandler(
    filename = paste0("top_concepts.", input$summarise_large_scale_characteristics_table_most_common_format),
    content = function(file) {
      gt::gtsave(getSummariseLargeScaleCharacteristicsTableMostCommon(), file)
    }
  )
  getSummariseLargeScaleCharacteristicsPlotCompared <- shiny::reactive({
    if (input$summarise_large_scale_characteristics_plot_compared_missings) {
      mis <- 0
    } else {
      mis <- NULL
    }
    getSummariseLargeScaleCharacteristicsData() |>
      CohortCharacteristics::plotComparedLargeScaleCharacteristics(
        colour = input$summarise_large_scale_characteristics_plot_compared_colour,
        reference = input$summarise_large_scale_characteristics_plot_compared_reference,
        facet = input$summarise_large_scale_characteristics_plot_compared_facet,
        missings = mis
      )
  })
  output$summarise_large_scale_characteristics_plot_compared <- plotly::renderPlotly({
    getSummariseLargeScaleCharacteristicsPlotCompared()
  })
  shiny::observeEvent(input$summarise_large_scale_characteristics_plot_compared_colour, {
    opts <- values[[paste0("summarise_large_scale_characteristics_", input$summarise_large_scale_characteristics_plot_compared_colour)]]
    shinyWidgets::updatePickerInput(
      inputId = "summarise_large_scale_characteristics_plot_compared_reference",
      choices = opts,
      selected = opts[1]
    )
  })
  # incidence -----
  ## update message if filter is changed
  shiny::observeEvent(input$incidence_cdm_name,
                      {
                        updateButtons$incidence <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$incidence_outcome_cohort_name,
                      {
                        updateButtons$incidence <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$incidence_maternal_age,
                      {
                        updateButtons$incidence <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$incidence_incidence_start_date,
                      {
                        updateButtons$incidence <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$incidence_analysis_interval,
                      {
                        updateButtons$incidence <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$incidence_analysis_censor_cohort_name,
                      {
                        updateButtons$incidence <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$incidence_analysis_complete_database_intervals,
                      {
                        updateButtons$incidence <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$incidence_analysis_outcome_washout,
                      {
                        updateButtons$incidence <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$incidence_analysis_repeated_events,
                      {
                        updateButtons$incidence <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$incidence_denominator_days_prior_observation,
                      {
                        updateButtons$incidence <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$incidence_denominator_end_date,
                      {
                        updateButtons$incidence <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$incidence_denominator_start_date,
                      {
                        updateButtons$incidence <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$incidence_variable_name,
                      {
                        updateButtons$incidence <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$incidence_estimate_name,
                      {
                        updateButtons$incidence <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$incidence, {
    if (updateButtons$incidence == TRUE) {
      output$update_message_incidence <- shiny::renderText("Filters have changed please consider to use the update content button!")
    } else {
      output$update_message_incidence <- shiny::renderText("")
    }
  })
  shiny::observeEvent(input$update_incidence, {
    updateButtons$incidence <- FALSE
  })
  
  ## get incidence data
  getIncidenceData <- shiny::eventReactive(input$update_incidence, {
    data[["incidence"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$incidence_cdm_name,
        .data$variable_name %in% input$incidence_variable_name,
        .data$estimate_name %in% input$incidence_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$outcome_cohort_name %in% input$incidence_outcome_cohort_name) |>
      omopgenerics::filterStrata(.data$maternal_age %in% input$incidence_maternal_age) |>
      omopgenerics::filterAdditional(
        .data$incidence_start_date %in% input$incidence_incidence_start_date,
      ) |>
      omopgenerics::filterSettings(
        .data$denominator_end_date %in% input$incidence_denominator_end_date,
        .data$denominator_start_date %in% input$incidence_denominator_start_date
      )
  })
  getIncidenceTidy <- shiny::reactive({
    tidyDT(getIncidenceData(), input$incidence_tidy_columns, input$incidence_tidy_pivot_estimates)
  })
  output$incidence_tidy <- DT::renderDT({
    getIncidenceTidy()
  })
  output$incidence_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getIncidenceData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getIncidenceTable <- shiny::reactive({
    res <- getIncidenceData()
    res |>
      IncidencePrevalence::tableIncidence(
        header = input$incidence_table_header,
        groupColumn = input$incidence_table_group_column,
        hide = input$incidence_table_hide,
        settingsColumn = omopgenerics::settingsColumns(res)
      )
  })
  output$incidence_table <- gt::render_gt({
    getIncidenceTable()
  })
  output$incidence_table_download <- shiny::downloadHandler(
    filename = paste0("table_incidence.", input$incidence_table_format),
    content = function(file) {
      gt::gtsave(getIncidenceTable(), file)
    }
  )
  getIncidencePlot <- shiny::reactive({
    getIncidenceData() |>
      IncidencePrevalence::plotIncidence(
        x = input$incidence_plot_x,
        facet = input$incidence_plot_facet,
        colour = input$incidence_plot_colour,
        ribbon = input$incidence_plot_ribbon,
        line = input$incidence_plot_line
      )
  })
  output$incidence_plot <- shiny::renderUI({
    x <- getIncidencePlot()
    renderInteractivePlot(x, input$incidence_plot_interactive)
  })
  output$incidence_plot_download <- shiny::downloadHandler(
    filename = "plot_incidence.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getIncidencePlot(),
        width = as.numeric(input$incidence_plot_width),
        height = as.numeric(input$incidence_plot_height),
        units = input$incidence_plot_units,
        dpi = as.numeric(input$incidence_plot_dpi)
      )
    }
  )
  getIncidencePlotPopulation <- shiny::reactive({
    getIncidenceData() |>
      IncidencePrevalence::plotIncidencePopulation(
        facet = input$incidence_plot_population_facet,
        colour = input$incidence_plot_population_colour
      )
  })
  output$incidence_plot_population <- shiny::renderUI({
    x <- getIncidencePlotPopulation()
    renderInteractivePlot(x, input$incidence_plot_population_interactive)
  })
  # incidence_attrition -----
  ## update message if filter is changed
  shiny::observeEvent(input$incidence_attrition_cdm_name,
                      {
                        updateButtons$incidence_attrition <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$incidence_attrition_analysis_censor_cohort_name,
                      {
                        updateButtons$incidence_attrition <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$incidence_attrition_analysis_complete_database_intervals,
                      {
                        updateButtons$incidence_attrition <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$incidence_attrition_analysis_outcome_washout,
                      {
                        updateButtons$incidence_attrition <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$incidence_attrition_analysis_repeated_events,
                      {
                        updateButtons$incidence_attrition <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$incidence_attrition_denominator_days_prior_observation,
                      {
                        updateButtons$incidence_attrition <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$incidence_attrition_denominator_end_date,
                      {
                        updateButtons$incidence_attrition <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$incidence_attrition_denominator_start_date,
                      {
                        updateButtons$incidence_attrition <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$incidence_attrition_variable_name,
                      {
                        updateButtons$incidence_attrition <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$incidence_attrition, {
    if (updateButtons$incidence_attrition == TRUE) {
      output$update_message_incidence_attrition <- shiny::renderText("Filters have changed please consider to use the update content button!")
    } else {
      output$update_message_incidence_attrition <- shiny::renderText("")
    }
  })
  shiny::observeEvent(input$update_incidence_attrition, {
    updateButtons$incidence_attrition <- FALSE
  })
  
  ## get incidence_attrition data
  getIncidenceAttritionData <- shiny::eventReactive(input$update_incidence_attrition, {
    data[["incidence_attrition"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$incidence_attrition_cdm_name,
        .data$variable_name %in% input$incidence_attrition_variable_name
      ) |>
      omopgenerics::filterSettings(
        .data$analysis_censor_cohort_name %in% input$incidence_attrition_analysis_censor_cohort_name,
        .data$analysis_complete_database_intervals %in% input$incidence_attrition_analysis_complete_database_intervals,
        .data$analysis_outcome_washout %in% input$incidence_attrition_analysis_outcome_washout,
        .data$analysis_repeated_events %in% input$incidence_attrition_analysis_repeated_events,
        .data$denominator_days_prior_observation %in% input$incidence_attrition_denominator_days_prior_observation,
        .data$denominator_end_date %in% input$incidence_attrition_denominator_end_date,
        .data$denominator_start_date %in% input$incidence_attrition_denominator_start_date
      )
  })
  getIncidenceAttritionTidy <- shiny::reactive({
    tidyDT(getIncidenceAttritionData(), input$incidence_attrition_tidy_columns, input$incidence_attrition_tidy_pivot_estimates)
  })
  output$incidence_attrition_tidy <- DT::renderDT({
    getIncidenceAttritionTidy()
  })
  output$incidence_attrition_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getIncidenceAttritionData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getIncidenceAttritionTable <- shiny::reactive({
    res <- getIncidenceAttritionData()
    res |>
      IncidencePrevalence::tableIncidenceAttrition(
        header = input$incidence_attrition_table_header,
        settingsColumn = omopgenerics::settingsColumns(res),
        groupColumn = input$incidence_attrition_table_group_column,
        hide = input$incidence_attrition_table_hide
      )
  })
  output$incidence_attrition_table <- gt::render_gt({
    getIncidenceAttritionTable()
  })
  output$incidence_attrition_table_download <- shiny::downloadHandler(
    filename = paste0("table_incidence_attrition.", input$incidence_attrition_table_format),
    content = function(file) {
      gt::gtsave(getIncidenceAttritionTable(), file)
    }
  )
}
