---
title: "Supplementary Material"
subtitle: "Cumulative incidence and characterisation of adverse events during pregnancy: a multi-country European cohort study"
format:
  docx:
    reference-doc: ref.docx
    fig-cap-location: top
execute:
  echo: false
  message: false
  warning: false
---


```{r}
library(CohortCharacteristics)
library(dplyr)
library(ggplot2)
library(IncidencePrevalence)
library(markdown)
library(omopgenerics)
library(OmopSketch)
library(tidyr)
library(visOmopResults)
library(CohortSurvival)
library(flextable)
library(lme4)
library(broom)     
library(glmmTMB)
library(purrr)
library(patchwork)
library(ggh4x)

# whether to run meta analysis
runMetaAnalysis <- FALSE

# preprocess data if it has not been done
fileData <- file.path(getwd(), "data", "shinyData.RData")
if (!file.exists(fileData)) {
  source(file.path(getwd(), "data", "preprocess.R"))
}

# load shiny data
load(fileData)

# source functions
source(file.path(getwd(), "functions.R"))

# Quarto options
knitr::opts_chunk$set(
  out.width  = "95%",  # figures occupy ~95% of document width
  out.height = "auto",
  dpi        = 360,    # ensure figure quality
  fig.width  = 9,      # default aspect ratio (can be overridden per-figure)
  fig.height = 6,
  results    = "asis"  # enable Markdown produced via cat() inside chunks
)

maeCode <- c(
  "stillbirth", 
  
  "gestational_diabetes", "antepartum_haemorrhage", 
  
  "preeclampsia", "eclampsia", "hellp",  
  
  "preterm_labour", "postpartum_haemorrhage"
)
maeClean <- c(
  "Stillbirth",
  
  "Gestational diabetes mellitus", "Antepartum haemorrhage", 
  
  "Pre-eclampsia", "Eclampsia", "HELLP syndrome", 
  
  "Preterm delivery", "Postpartum haemorrhage"
)
aesiCode <- c(
  "pulmonary_embolism", "deep_vein_thrombosis",
  "immune_thrombocytopenia", "bells_palsy"
)
aesiClean <- c(
  'Pulmonary embolism', 'Deep vein thrombosis',
  'Immune thrombocytopenia', 'Bell’s palsy'
)
excludeCPRD <- c("Miscarriage", "Dysfunctional labour")
excludeSCIFI <- c("Ectopic pregnancy")
dbOrder <- c("SCIFI-PEARL", "NLHR", "SIDIAP")

setGlobalTableOptions(type = "flextable")

# characterisation ----
characteristics <- data$summarise_characteristics |>
  filter(cdm_name %in% dbOrder) |>
  filter(!grepl("_sens", group_level)) |>
  dplyr::mutate( 
    variable_name = factor(
      variable_name,
      levels = c(
        "Number records", 
        "Number subjects",
        "Maternal age", 
        "Maternal age group",
        "Trimester",
        "Days in cohort", 
        "Covariates in the past year",
        "History of comorbidities", 
        "Medications in the past 6 months",
        "Maternal Adverse Events during pregnancy",
        "Maternal Adverse Events during previous pregnancy",
        "Season",
        "Socioeconomic status",
        "Ethnicity",
        "Nationallity",
        "Birth continent",
        "Pregnancy start period"
      ),
      labels = c(
        "Number\npregnancies", 
        "Number\nsubjects",
        "Maternal age", 
        "Maternal age\ngroup",
        "Trimester",
        "Pregnancy length\n(days)",
        "Comorbidities\n(prior year)",
        "Comorbidities\n(any-time before)",
        "Medications\n(prior 6 months)",
        "Maternal Adverse Events\n(during pregnancy)",
        "Maternal Adverse Events\n(prior pregnancy)",
        "Season",
        "Socioeconomic status",
        "Ethnicity",
        "Nationallity",
        "Birth continent",
        "Pregnancy start period"
      )
    ),
    variable_level = factor(
      variable_level,
      levels = c(
        "12 to 17", "18 to 34", "35 to 55", "-",
        
        paste0("Trimester ", 1:3), "Postpartum",
        
        "Obesity", "Depression", "Anxiety", "Alcohol misuse dependence",
        
        "Asthma", "Diabetes", "Thyroid disorder",
        "Essential hypertension",
        "Systemic lupus erythematosus", "Hiv",
        "Uterus malformations", "Polycystic ovary syndrome",
        "Chronic viral hepatitis", "Inflammatory bowel disease",
        
        "Antidepressants", "Antiinflammatory antirheumatic", "Nsaids",
        "Opioids", "Treatment acid related disorder", "Antiepileptics",
        "Diabetes treatments", "Antithrombotics", "Immunosupressants",
        "Corticosteroids",
        
        maeCode,
        
        "Autumn", "Spring", "Summer", "Winter",
        
        "Q1", "Q2", "Q3", "Q4", "Q5", "U1", "U2", "U3", "U4", "U5", "R", "0n", 
        
        "White", "Asian", "Black", 
        
        "Asia", "Central/south america", "Europe", "Africa", "North america", "Oceania", "Missing",
        
        "Pre covid-19", "Covid-19 main outbreak", "Post covid-19 main outbreak"
      ),
      labels = c(
        "12 to 17", "18 to 34", "35 to 55", "-",
        
        paste0("Trimester ", 1:3), "Postpartum",
        
        "Obesity", "Depression", "Anxiety", "Alcohol misuse\ndependence",
        
        "Asthma", "Diabetes", "Thyroid disorder",
        "Essential\nhypertension",
        "SLE", "HIV",
        "Uterus malformations", "PCOS",
        "Chronic viral hepatitis", "Inflammatory bowel disease",
        
        "Antidepressants", "Antiinflammatory/\nantirheumatic", "NSAIDs",
        "Opioids", "Acid-related disorder\ntreatments", "Antiepileptics",
        "Diabetes treatments", "Antithrombotics", "Immunosupressants",
        "Corticosteroids",
        
        maeClean,
        
        "Winter", "Autumn", "Spring", "Summer",
        
        "Q1", "Q2", "Q3", "Q4", "Q5", "U1", "U2", "U3", "U4", "U5", "R", "0n", 
        
        "White", "Asian", "Black", 
        "Asia", "Central/south america", "Europe", "Africa", "North america", "Oceania", "Missing",
        
        "Pre COVID-19", "COVID-19 main outbreak", "Post COVID-19 main outbreak"
      )
    )
  ) |>
  filter(!is.na(variable_name), !is.na(group_level)) |>
  filter(!(cdm_name == "CPRD GOLD" & variable_name %in% excludeCPRD)) |>
  filter(!(cdm_name == "CPRD GOLD" & grepl(paste0(toSnakeCase(excludeCPRD), collapse = "|"), group_level))) |>
  filter(!(cdm_name == "SCIFI-PEARL" & variable_name %in% excludeSCIFI)) |>
  filter(!(cdm_name == "SCIFI-PEARL" & grepl(paste0(toSnakeCase(excludeSCIFI), collapse = "|"), group_level))) |>
  mutate(
    group_level = as.character(factor(
      group_level, 
      levels = c(maeCode, paste0(maeCode, "_matched"), paste0(maeCode, "_sampled"), aesiCode, paste0(aesiCode, "_matched"), paste0(aesiCode, "_sampled")), 
      labels = c(maeClean, paste0(maeClean, "_matched"), paste0(maeClean, "_sampled"), aesiClean, paste0(aesiClean, "_matched"), paste0(aesiClean, "_sampled"))
    ))
  ) |>
  filter(!is.na(group_level)) |>
  filter(!(gsub("_matched|_sampled", "", group_level) == variable_level & variable_name == "Maternal Adverse Events\n(during pregnancy)")) 

# SURVIVAL ----
survival <-data$survival |>
  filter(cdm_name %in% dbOrder) |>
  filter(strata_name %in% c("overall", "maternal_age_group")) |>
  omopgenerics::filterSettings(result_type == "survival_probability") |>
  tidy() |>
  dplyr::mutate(
    outcome = factor(
      .data$outcome, 
      levels = c(maeCode, aesiCode), 
      labels = c(maeClean, aesiClean), 
    ),
    cdm_name = factor(cdm_name, levels = dbOrder),
    time = as.numeric(time),
    estimate = 1 - estimate,
    estimate_95CI_lower = 1 - estimate_95CI_lower,
    estimate_95CI_upper = 1 - estimate_95CI_upper
  ) |>
  dplyr::filter(!is.na(outcome)) 

limit_grid <- bind_rows(
  survival |>
    filter(target_cohort == "pregnancy_denominator") |>
    group_by(outcome) |>
    summarise(facet_max = max(estimate, na.rm = TRUE), .groups = "drop") |>
    mutate(upper_limit = facet_max),
  survival |>
    filter(target_cohort %in% c("postpartum_6_weeks_denominator", "postpartum_12_weeks_denominator")) |>
    group_by(outcome) |>
    summarise(facet_max = max(estimate, na.rm = TRUE), .groups = "drop") |>
    mutate(upper_limit = facet_max)
)

custom_scales_list <- pmap(limit_grid, function(outcome, maternal_age_group, upper_limit, ...) {
  as.formula(
    paste0(
      'outcome == "', outcome, '" ~ ',
      'scale_y_continuous(limits = c(0, ', upper_limit, '), 
                          expand = expansion(mult = c(0.05, 0.1)),
                          oob = scales::rescale_none)'
    )
  )
})

colors <- c("#C94A5A", "#4A6FE3", "#4FAE6A", "#E08A3C")
cif <- function(x, ylimits, colors = c("#edae49", "#d1495b", "#00798c")) {
  x |>
    ggplot(aes(x = time, y = estimate, color = maternal_age_group, fill = maternal_age_group, group = maternal_age_group)) +
    geom_ribbon(
      aes(
        ymin = estimate_95CI_lower, 
        ymax = estimate_95CI_upper 
      ),
      alpha = 0.15,
      color = NA
    ) +
    geom_line() +
    facet_grid(outcome ~ cdm_name, scales = "free",  labeller = labeller(outcome = label_wrap_gen(width = 10)),) +
    facetted_pos_scales(y = ylimits) +
    scale_color_manual(values = colors) +
    scale_fill_manual(values = colors) +
    theme_bw() +
    theme(
      strip.text = element_text(face = "bold", size = 10, colour = "black"),
      legend.position = "top",
      legend.title = element_text(face = "bold"),
      panel.grid.minor = element_blank(),
      plot.title = element_text(face = "bold", size = 14)
    ) +
    guides(
      color = guide_legend(title = "Data source"),
      fill  = guide_legend(title = "Data source")
    ) 
}

tabNum <- 1
figNum <- 1
```


```{r}
cat(paste0("# Supplementary Table ", tabNum, ". Characteristics of all pregnancies included over the study period, stratified by data source.\n"))
tabNum <- tabNum + 1
 
data$summarise_characteristics |>
  dplyr::filter(group_level == "pregnancy_denominator", strata_name == "overall") |>
  dplyr::mutate(
    cdm_name = factor(cdm_name, levels = dbOrder, labels = c("SCIFI-PEARL (Sweden)", "NLHR (Norway)", "SIDIAP (Spain)")),
    variable_name = factor(
      variable_name,
      levels = c(
        "Number records", 
        "Number subjects",
        "Maternal age", 
        "Maternal age group",
        "Days in cohort", 
        "Pre-Pregnancy Smoke",
        "Covariates in the past year",
        "History of comorbidities", 
        "Medications in the past 6 months"
      ),
      labels = c(
        "Number\npregnancies, N", 
        "Number\nsubjects, N",
        "Maternal age,\nMedian [IQR]", 
        "Maternal age\ngroup, N(%)",
        "Pregnancy length\n(days), Median [IQR]", 
        "Smoking status,\nN(%)",
        "Comorbidities\n(prior year), N(%)",
        "Comorbidities\n(any-time before),\nN(%)",
        "Medications\n(prior 6 months),\nN(%)"
      )
    ),
    variable_level = factor(
      variable_level,
      levels = c(
        "12 to 17", "18 to 34", "35 to 55", "-",
        
        "No", "Yes", "No smoker", "Smoker", "Never smoker", "Former smoker", "Current some day smoker", "Missing",          
        
        "Obesity", "Depression", "Anxiety", "Alcohol misuse dependence",
        
        "Asthma", "Diabetes", "Thyroid disorder",
        "Essential hypertension",
        "Systemic lupus erythematosus", "Hiv",
        "Uterus malformations", "Polycystic ovary syndrome",
        "Chronic viral hepatitis", "Inflammatory bowel disease",
        
        "Antidepressants", "Antiinflammatory antirheumatic", "Nsaids",
        "Opioids", "Treatment acid related disorder", "Antiepileptics",
        "Diabetes treatments", "Antithrombotics", "Immunosupressants",
        "Corticosteroids"
      ),
      labels = c(
        "12 to 17", "18 to 34", "35 to 55", "-",
        
        "No", "Yes", "No", "Yes", "No", "Former smoker", "Yes", "Missing",   
        
        "Obesity", "Depression", "Anxiety", "Alcohol misuse\ndependence",
        
        "Asthma", "Diabetes", "Thyroid disorder",
        "Essential\nhypertension",
        "SLE", "HIV",
        "Uterus malformations", "PCOS",
        "Chronic viral\nhepatitis", "Inflammatory\nbowel disease",
        
        "Antidepressants", "Antiinflammatory/\nantirheumatic", "NSAIDs",
        "Opioids", "Acid-related disorder\ntreatments", "Antiepileptics",
        "Diabetes treatments", "Antithrombotics", "Immunosupressants",
        "Corticosteroids"
      )
    )
  ) |>
  dplyr::filter(!is.na(variable_name), !is.na(cdm_name)) |>
  dplyr::arrange(cdm_name, variable_name, variable_level) |>
  visOmopTable(
    estimateName = c(
      "A" = "<count> (<percentage>%)",
      "b" = "<count>",
      "c" = "<median> [<q25> - <q75>]"
    ),
    rename = c("Data source" = "cdm_name"),
    header = "cdm_name",
    hide = c("cohort_name", strataColumns(data$summarise_characteristics), "estimate_name"),
    .options = list(keepNotFormatted = FALSE, groupAsColumn = TRUE, decimalMark = "·", bigMark = " "),
    groupColumn = "variable_name",
    factor = list(
      variable_name = c(
        "Number\npregnancies, N", 
        "Number\nsubjects, N",
        "Maternal age,\nMedian [IQR]", 
        "Maternal age\ngroup, N(%)",
        "Pregnancy length\n(days), Median [IQR]", 
        "Smoking status,\nN(%)",
        "Comorbidities\n(prior year), N(%)",
        "Comorbidities\n(any-time before),\nN(%)",
        "Medications\n(prior 6 months),\nN(%)"
      ),
      variable_level = c(
        "12 to 17", "18 to 34", "35 to 55", "-", NA,
        
        "No", "Yes", "Former smoker", "Missing",   
        
        "Obesity", "Depression", "Anxiety", "Alcohol misuse\ndependence",
        
        "Asthma", "Diabetes", "Thyroid disorder",
        "Essential\nhypertension",
        "SLE", "HIV",
        "Uterus malformations", "PCOS",
        "Chronic viral\nhepatitis", "Inflammatory\nbowel disease",
        
        "Antidepressants", "Antiinflammatory/\nantirheumatic", "NSAIDs",
        "Opioids", "Acid-related disorder\ntreatments", "Antiepileptics",
        "Diabetes treatments", "Antithrombotics", "Immunosupressants",
        "Corticosteroids"
      )
    )
  ) |>
  set_table_properties(layout = "autofit") |>
  font(fontname = "calibri", part = "all") |>
  fontsize(size = 9, part = "body") |>
  fontsize(size = 10, part = "header") 

  footer <- paste0("The study enrolment period went from January 2018 to December 2023 for SCIFI-PEARL, March 2023 for NLHR, and March 2024 for SIDIAP. End dates correspond to 9 months before pregnancy data cut-off date. All pregnancies starting during enrolment period, aged 12 to 55 years, and with at least 1 year of previous observation in the data source were included\n
Smoking status was estimated differently for each database. In SCIFI-PEARL and NLHR, it is a binary variable from the birth registry indicating smoking status before pregnancy and is collected in the first maternal healthcare visit. In SIDIAP it is based on primary care collected records, as a proxy for maternal smoking we used the latest record from 5 years before pregnancy until pregnancy end.\n
Abbreviations: SCIFI-PEARL = Swedish Covid-19 Investigation for Future Insights – a Population Epidemiology Approach using Register Linkage; NLHR = Norwegian Linked Health Registries; SIDIAP = Information System for Research in Primary Care Database; SLE = Systemic Lupus Erythematosus; HIV= Human Immunodeficiency Virus; PCOS = Polycystic Ovary Syndrome

")
  cat(paste0(
    ':::{custom-style="FooterNuria"}\n',
    footer, '\n',
    '::: \n'
  ))
    cat("\n\n\\pagebreak\n")
```



```{r}
# CUMULATIVE INCIDENCE 
outcomesPregnancy <- c(maeClean[maeClean != "Postpartum haemorrhage"], aesiClean)

for (out in outcomesPregnancy) {
  cat(paste0("# Supplementary Table ", tabNum, ". Cumulative incidence estimates of ", out, " during pregnancy, stratified by maternal age and data source.\n"))
  tabNum <- tabNum + 1
  times <- c(20, 24, 28, 32, 34, 37, 40, 42)
  if (out %in% aesiClean) {
    times <- c(12, times)
  }
  survival |>
    filter(outcome == out) |>
    filter(target_cohort != "pregnancy_and_12_weeks_postpartum") |>
    # group_by(cdm_name, outcome, maternal_age_group) |>
    filter(time > 19*7) |>
    filter(
      time %in% c(times*7)
    ) |>
    mutate(
      "Gestational week" = factor(time, levels = seq.int(0, 330, 7), labels = paste0("Week ", 0:length(seq.int(0, 322, 7)))),
      maternal_age_group = if_else(
        maternal_age_group == "overall", 
        "Overall",
        paste0(maternal_age_group, " years")
      ),
      cdm_name = case_when(
        cdm_name == "NLHR" ~ paste0(cdm_name, " (Norway)"),
        cdm_name == "SCIFI-PEARL" ~ paste0(cdm_name, " (Sweden)"),
        cdm_name == "SIDIAP" ~ paste0(cdm_name, " (Spain)")
      )
    ) |>
    # ungroup() |>
    filter(!(outcome == "Postpartum haemorrhage" & target_cohort == "pregnancy_denominator")) |>
    select(cdm_name, outcome, maternal_age_group, time, estimate, estimate_95CI_lower, estimate_95CI_upper, `Gestational week`) |>
    pivot_longer(
      cols = c("estimate", "estimate_95CI_lower", "estimate_95CI_upper"),
      names_to = "estimate_name",
      values_to = "estimate_value"
    ) |>
    mutate(
      estimate_type = "numeric",
      estimate_value = 100*estimate_value
    ) |>
    filter(outcome != "Postpartum haemorrhage") |>
    visTable(
      estimateName = c("Cumulative Incidence (95% CI)" = "<estimate> (<estimate_95CI_upper> - <estimate_95CI_lower>)"),
      hide = c("estimate_type", "outcome", "time"),
      header = c("estimate_name", "cdm_name", "maternal_age_group"),
      .options = list(includeHeaderName = FALSE)
    ) |>
    set_table_properties(layout = "autofit") |>
    font(fontname = "calibri", part = "all") |>
    fontsize(size = 9, part = "body") |>
    fontsize(size = 9, part = "header") |>
    border(
      border = officer::fp_border(color = "#c8c8c8"),
      part = "all"
    ) |>
    flextable::flextable_to_rmd()
  
  footer <- paste0("Data are presented as cumulative incidence percentages with 95% confidence intervals. Estimates are reported for gestational weeks 20, 24, 28, 32, 34 (late preterm threshold), 37 (transition to full-term gestation), 40 (expected delivery), and 42 (post-term gestation). Estimates for post-term gestation (week 41 onwards) and for the youngest maternal age group (12–17 years) should be interpreted with caution because of the limited number of pregnancies remaining at risk.\n
Abbreviations: CI = confidence interval; NLHR = Norwegian Linked Health Registries; SCIFI-PEARL = Swedish Covid-19 Investigation for Future Insights – a Population Epidemiology Approach using Register Linkage; SIDIAP = Information System for Research in Primary Care Database (Spain).")
  cat(paste0(
    ':::{custom-style="FooterNuria"}\n',
    footer, '\n',
    '::: \n'
  ))
    cat("\n\n\\pagebreak\n")
}

# postpartum
out <- "Postpartum haemorrhage"
cat(paste0("# Supplementary Table ", tabNum, ". Postpartum week–specific cumulative incidence of postpartum haemorrhage, stratified by maternal age and data source.\n"))
tabNum <- tabNum + 1
survival |>
  # filter(outcome == out) |>
  filter(target_cohort == "postpartum_12_weeks_denominator") |>
  filter(
    time %in% c(1, 8, 15, 36, 57, 78)
  ) |>
  mutate(
    "Postpartum week" = factor(time, levels = seq.int(1, 330, 7), labels = paste0("Week ", 1:length(seq.int(1, 330, 7)))),
    maternal_age_group = if_else(
      maternal_age_group == "overall", 
      "Overall",
      paste0(maternal_age_group, " years")
    ),
    cdm_name = case_when(
      cdm_name == "NLHR" ~ paste0(cdm_name, " (Norway)"),
      cdm_name == "SCIFI-PEARL" ~ paste0(cdm_name, " (Sweden)"),
      cdm_name == "SIDIAP" ~ paste0(cdm_name, " (Spain)")
    )
  ) |>
  filter(!(outcome == "Postpartum haemorrhage" & target_cohort == "pregnancy_denominator")) |>
  select(cdm_name, outcome, maternal_age_group, time, estimate, estimate_95CI_lower, estimate_95CI_upper, `Postpartum week`) |>
  pivot_longer(
    cols = c("estimate", "estimate_95CI_lower", "estimate_95CI_upper"),
    names_to = "estimate_name",
    values_to = "estimate_value"
  ) |>
  mutate(
    estimate_type = "numeric",
    estimate_value = 100*estimate_value
  ) |>
  visTable(
    estimateName = c("Cumulative Incidence (95% CI)" = "<estimate> (<estimate_95CI_upper> - <estimate_95CI_lower>)"),
    hide = c("estimate_type", "outcome", "time"),
    # groupColumn = "cdm_name",
    header = c("estimate_name", "cdm_name", "maternal_age_group"),
    .options = list(includeHeaderName = FALSE)
  ) |>
  set_table_properties(layout = "autofit") |>
  font(fontname = "calibri", part = "all") |>
  fontsize(size = 9, part = "body") |>
  fontsize(size = 9, part = "header") |>
  border(
    border = officer::fp_border(color = "#c8c8c8"),
    part = "all"
  ) |>
  flextable::flextable_to_rmd()

footer <- paste0("Data are presented as cumulative incidence percentages with 95% confidence intervals. Estimates are reported for postpartum weeks 1, 2, 3, 6, 9, and 12 following delivery. Estimates for the youngest maternal age group (12–17 years) should be interpreted with caution because of the limited number of pregnancies remaining at risk.\n
Abbreviations: CI = confidence interval; NLHR = Norwegian Linked Health Registries; SCIFI-PEARL = Swedish Covid-19 Investigation for Future Insights – a Population Epidemiology Approach using Register Linkage; SIDIAP = Information System for Research in Primary Care Database (Spain).")
cat(paste0(
  ':::{custom-style="FooterNuria"}\n',
  footer, '\n',
  '::: \n'
))
  cat("\n\n\\pagebreak\n")
```


```{r}
# DENOMINATOR
outcomesPregnancy <- c(maeClean[maeClean != "Postpartum haemorrhage"], aesiClean)

for (out in outcomesPregnancy) {
  cat(paste0("# Supplementary Table ", tabNum, ". Number of pregnancies at risk, events, and censored pregnancies by gestational month used in the cumulative incidence estimation of ", out, ", stratified by maternal age and data source.\n"))
  tabNum <- tabNum + 1
  
 x <- data$survival |>
    filter(cdm_name %in% dbOrder) |>
    filter(strata_name %in% c("overall", "maternal_age_group")) |>
    filter(variable_level %in% c(aesiCode, maeCode)) |>
    asSurvivalResult()
 
 attr(x, "events") |>
   mutate(outcome = factor(outcome, c(maeCode, aesiCode), c(maeClean, aesiClean))) |>
   filter(outcome == out) |>
   filter(target_cohort != "pregnancy_and_12_weeks_postpartum") |>
    filter(time > 19*7 & time <= 300) |>
    mutate(
      "Gestational month" = factor(time, levels = c(150, 180, 210, 240, 270, 300), labels = paste0("Day ", c(150, 180, 210, 240, 270, 300))),
      maternal_age_group = if_else(
        maternal_age_group == "overall", 
        "Overall",
        paste0(maternal_age_group, " years")
      ),
      cdm_name = case_when(
        cdm_name == "NLHR" ~ paste0(cdm_name, " (Norway)"),
        cdm_name == "SCIFI-PEARL" ~ paste0(cdm_name, " (Sweden)"),
        cdm_name == "SIDIAP" ~ paste0(cdm_name, " (Spain)")
      )
    ) |>
    # ungroup() |>
    filter(!(outcome == "Postpartum haemorrhage" & target_cohort == "pregnancy_denominator"), !is.na(`Gestational month`)) |>
    select(cdm_name, outcome, maternal_age_group, `Pregnancies at risk` = n_risk, `Events` = n_events, `Censored pregnancies` = n_censor, `Gestational month`) |>
    pivot_longer(
      cols = c("Pregnancies at risk", "Events", "Censored pregnancies"),
      names_to = "estimate_name",
      values_to = "estimate_value"
    ) |>
    mutate(
      estimate_type = "integer",
      # estimate_value = 100*estimate_value
    ) |>
    filter(outcome != "Postpartum haemorrhage") |>
   arrange(`Gestational month`) |>
   visTable(
      # estimateName = c("Cumulative Incidence (95% CI)" = "<estimate> (<estimate_95CI_upper> - <estimate_95CI_lower>)"),
      hide = c("estimate_type", "outcome", "time"),
      groupColumn = "cdm_name",
      header = c("maternal_age_group", "estimate_name"),
      .options = list(includeHeaderName = FALSE)
    ) |>
    set_table_properties(layout = "autofit") |>
    font(fontname = "calibri", part = "all") |>
    fontsize(size = 9, part = "body") |>
    fontsize(size = 9, part = "header") |>
    border(
      border = officer::fp_border(color = "#c8c8c8"),
      part = "all"
    ) |>
    flextable::flextable_to_rmd()
  
  footer <- paste0("Censored pregnancies represent pregnancies that reached the end of follow-up without experiencing the outcome of interest. Cells marked with “—” indicate counts fewer than five, which were suppressed in accordance with data privacy regulations.
Abbreviations: NLHR = Norwegian Linked Health Registries; SCIFI-PEARL = Swedish Covid-19 Investigation for Future Insights – a Population Epidemiology Approach using Register Linkage; SIDIAP = Information System for Research in Primary Care Database (Spain).")
  cat(paste0(
    ':::{custom-style="FooterNuria"}\n',
    footer, '\n',
    '::: \n'
  ))
    cat("\n\n\\pagebreak\n")
}

# postpartum
out <- "Postpartum haemorrhage"
cat(paste0("# Supplementary Table ", tabNum, ". Number of pregnancies at risk, events, and censored pregnancies by gestational month used in the cumulative incidence estimation of ", out, ", stratified by maternal age and data source.\n"))
tabNum <- tabNum + 1

x <- data$survival |>
  filter(cdm_name %in% dbOrder) |>
  filter(strata_name %in% c("overall", "maternal_age_group")) |>
  asSurvivalResult()

attr(x, "events") |>
  filter(target_cohort == "postpartum_12_weeks_denominator") |>
  # filter(time > 19*7 & time <= 300) |>
  mutate(
    "Month" = factor(time, levels = 0:310, labels = paste0("Day ", 0:310)),
    maternal_age_group = if_else(
      maternal_age_group == "overall", 
      "Overall",
      paste0(maternal_age_group, " years")
    ),
    cdm_name = case_when(
      cdm_name == "NLHR" ~ paste0(cdm_name, " (Norway)"),
      cdm_name == "SCIFI-PEARL" ~ paste0(cdm_name, " (Sweden)"),
      cdm_name == "SIDIAP" ~ paste0(cdm_name, " (Spain)")
    )
  ) |>
  # ungroup() |>
  select(cdm_name, outcome, maternal_age_group, `Pregnancies at risk` = n_risk, `Events` = n_events, `Censored pregnancies` = n_censor, `Month`) |>
  pivot_longer(
    cols = c("Pregnancies at risk", "Events", "Censored pregnancies"),
    names_to = "estimate_name",
    values_to = "estimate_value"
  ) |>
  mutate(
    estimate_type = "integer",
    # estimate_value = 100*estimate_value
  ) |>
  filter(outcome != "Postpartum haemorrhage") |>
  arrange(`Month`) |>
  visTable(
    # estimateName = c("Cumulative Incidence (95% CI)" = "<estimate> (<estimate_95CI_upper> - <estimate_95CI_lower>)"),
    hide = c("estimate_type", "outcome", "time"),
    groupColumn = "cdm_name",
    header = c("maternal_age_group", "estimate_name"),
    .options = list(includeHeaderName = FALSE)
  ) |>
  set_table_properties(layout = "autofit") |>
  font(fontname = "calibri", part = "all") |>
  fontsize(size = 9, part = "body") |>
  fontsize(size = 9, part = "header") |>
  border(
    border = officer::fp_border(color = "#c8c8c8"),
    part = "all"
  ) |>
  flextable::flextable_to_rmd()

cat(paste0(
  ':::{custom-style="FooterNuria"}\n',
  footer, '\n',
  '::: \n'
))
  cat("\n\n\\pagebreak\n")
```


```{r, fig.width=22, fig.height=11}
filterOut <- bind_rows(
  # Miscarriage ----
  tibble(
    cohort_name = "Miscarriage",
    variable_name = "Maternal Adverse Events\n(during pregnancy)",
    variable_level = c("Miscarriage", "Stillbirth", "Gestational diabetes mellitus", "Antepartum haemorrhage", "Pre-eclampsia", "Eclampsia", "HELLP syndrome", "Preterm delivery", "Dysfunctional labour", "Postpartum haemorrhage")
  ),
  # Ectopic pregnancy ----
  tibble(
    cohort_name = "Ectopic pregnancy",
    variable_name = "Maternal Adverse Events\n(during pregnancy)",
    variable_level = c("Ectopic pregnancy", "Stillbirth", "Gestational diabetes mellitus", "Antepartum haemorrhage", "Pre-eclampsia", "Eclampsia", "HELLP syndrome", "Preterm delivery", "Dysfunctional labour", "Postpartum haemorrhage")
  ),
  # Stillbirth ----
  tibble(
    cohort_name = "Stillbirth",
    variable_name = "Maternal Adverse Events\n(during pregnancy)",
    variable_level = c("Miscarriage", "Stillbirth")
  ), 
  # Gestational diabetes mellitus ----
  tibble(
    cohort_name = "Gestational diabetes mellitus",
    variable_name = "Maternal Adverse Events\n(during pregnancy)",
    variable_level = c("Gestational diabetes mellitus")
  ),
  # Antepartum haemorrhage ----
  tibble(
    cohort_name = "Antepartum haemorrhage",
    variable_name = "Maternal Adverse Events\n(during pregnancy)",
    variable_level = c("Antepartum haemorrhage", "Miscarriage")
  ), 
  # Pre-eclampsia ----
  tibble(
    cohort_name = "Pre-eclampsia",
    variable_name = "Maternal Adverse Events\n(during pregnancy)",
    variable_level = c("Pre-eclampsia")
  ), 
  # Eclampsia ----
  tibble(
    cohort_name = "Eclampsia",
    variable_name = "Maternal Adverse Events\n(during pregnancy)",
    variable_level = c("Eclampsia")
  ), 
  # HELLP syndrome ----
  tibble(
    cohort_name = "HELLP syndrome",
    variable_name = "Maternal Adverse Events\n(during pregnancy)",
    variable_level = c("HELLP syndrome")
  ), 
  # Preterm delivery ----
  tibble(
    cohort_name = "Preterm delivery",
    variable_name = "Maternal Adverse Events\n(during pregnancy)",
    variable_level = c("Preterm delivery")
  ), 
  # Dysfunctional labour ----
  tibble(
    cohort_name = "Dysfunctional labour",
    variable_name = "Maternal Adverse Events\n(during pregnancy)",
    variable_level = c("Dysfunctional labour")
  )
)
  
# Figures comparison ----
xlim <- 1.1
smd <- characteristics |>
  filter(
    variable_name %in% c(
      "Comorbidities\n(prior year)",
      "Comorbidities\n(any-time before)",
      # "Medications\n(prior 6 months)",
      "Maternal Adverse Events\n(during pregnancy)",
      "Maternal Adverse Events\n(prior pregnancy)"
    ),
    grepl("sample|match", group_level),
    !variable_level %in% c("Alcohol misuse\ndependence", "HIV", "SLE", "Inflammatory bowel disease", "Chronic viral hepatitis", "Uterus malformations")
  ) |>
  splitAll() |>
  mutate(
    type = if_else(grepl("sampled", cohort_name), "sampled", "matched"),
    cohort_name = gsub("_sampled|_matched", "", cohort_name),
    estimate_value = as.numeric(estimate_value),
    cohort_name = factor(cohort_name, levels = c(maeClean, aesiClean)),
    variable_name = factor(
      variable_name, 
      levels = c("Comorbidities\n(prior year)", "Comorbidities\n(any-time before)", "Maternal Adverse Events\n(during pregnancy)", "Maternal Adverse Events\n(prior pregnancy)"),
      labels = c("Comorbidities", "Comorbidities", "Maternal Adverse Events\n(during pregnancy)", "Maternal Adverse Events\n(prior pregnancy)")
    ),
    cohort_group = case_when(
      cohort_name == "Stillbirth" ~ "Stillbirth",
      cohort_name %in% c("Gestational diabetes mellitus", "Antepartum haemorrhage") ~ "Non-hypertensive Pregnancy Complications",
      cohort_name %in% c("Pre-eclampsia", "Eclampsia", "HELLP syndrome" ) ~ "Hypertensive Disorders of Pregnancy"
    )
  ) |>
  filter(!is.na(cohort_name)) |>
  filter(variable_level != "Diabetes") |>
  anti_join(filterOut) |>
  # filter(!(as.character(cohort_name) == as.character(variable_level) & variable_name == 'Maternal Adverse Events during pregnancy')) |>
  select(!estimate_type) |>
  addSettings() |>
  pivot_wider(names_from = c("estimate_name", "type"), values_from = "estimate_value") |>
  mutate(
    smd = case_when(
      # variable_name == "Maternal age" ~ (mean_matched - mean_sampled)/sqrt(sd_matched + sd_sampled),
      is.na(percentage_matched) | is.na(percentage_sampled) ~ NA,
      percentage_matched == percentage_sampled ~ 0,
      .default = (percentage_sampled/100 - percentage_matched/100) / sqrt((percentage_sampled/100*(1-percentage_sampled/100) + percentage_matched/100*(1-percentage_matched/100))/2)
    ),
    variable_level = factor(variable_level, levels = rev(levels(characteristics$variable_level)))
  ) |>
  mutate(
    # Clamp the x-end for the segment at 2.0, but keep the original smd for the point
    smd_clipped = if_else(smd > xlim, xlim, NA),
    # Create a flag to identify where arrows are needed
    is_out_of_bounds = smd > xlim
  )

colors <- c("#4A6FE3", "#4FAE6A", "#E08A3C", "#C94A5A")

for (strataName in c("trimester", "maternal_age_group")) {
  
  if (strataName == "maternal_age_group") {
    strataLevels <- c("12 to 17", "18 to 34", "35 to 55")
    outcomeOut <- NULL
  } 
  
  if (strataName == "trimester")  {
    strataLevels <- c("Trimester 1", "Trimester 2", "Trimester 3")
    outcomeOut <- "Postpartum haemorrhage"
  }
  
  for (strataLevel in strataLevels) {
    strataLabel <- switch (strataLevel,
      "Trimester 1" = "first trimester occurrence",
      "Trimester 2" = "second trimester occurrence",
      "Trimester 3" = "third trimester occurrence",
      "12 to 17" = "maternal age group 12–17 years",
      "18 to 34" = "maternal age group 18–34 years",
      "35 to 55" = "maternal age group 35–55 years"
    )
    cat(paste0("# Supplementary Figure ", figNum, ". Standardised mean differences comparing pregnancies affected by each outcome with matched outcome-free pregnancies across data sources, stratified by ", strataLabel, ".\n"))
    figNum <- figNum + 1
    
    footer <- "\nThe figure shows Standardised mean differences (SMDs) for selected comorbidities, maternal adverse events occurring during the index pregnancy, and in previous pregnancies among pregnancies affected by the outcomes of interest in the study. Comparisons were performed separately for SCIFI-PEARL (Sweden), NLHR (Norway), and SIDIAP (Spain). Outcome-free pregnancies were matched on maternal age, gestational age (2-week bands), and calendar time (2-week bands). Positive SMD values indicate higher prevalence among pregnancies affected by the outcome compared with matched pregnancies without the outcome, whereas negative values indicate lower prevalence. Vertical dashed lines indicate SMD thresholds of ±0.1. These comparisons are descriptive and should not be interpreted as causal associations without targeted analysis."
    
    cat(paste0(
      ':::{custom-style="FooterNuria"}\n',
      footer, '\n',
      '::: \n'
    ))
    
    print(
      smd |>
        filter(.data[[strataName]] == strataLevel) |>
        filter(!cohort_name %in% outcomeOut) |>
        ggplot(aes(x = smd, y = variable_level, colour = cdm_name)) +
        geom_vline(xintercept = 0, linetype = "dashed", color = "black") + 
        geom_vline(xintercept = 0.1, linetype = "dashed", color = "gray") + 
        geom_vline(xintercept = -0.1, linetype = "dashed", color = "gray") + 
        geom_segment(aes(yend = variable_level, xend = 0), color = "#8b0000", size = 0.8) +
        geom_segment(
          aes(
            x = 0, 
            xend = smd_clipped, 
            yend = variable_level
          ), 
          color = "#8b0000", 
          linewidth = 0.8,
          arrow = arrow(length = unit(0.2, "cm")),
          na.rm = TRUE
        ) +
        coord_cartesian(xlim = c(-0.5, xlim)) +
        geom_point(size = 2.5, alpha = 0.8) +
        facet_grid(variable_name ~ cohort_name, 
                   scales = "free_y", 
                   space = "free", 
                   labeller = labeller(cohort_name = label_wrap_gen(width = 10)),
                   switch = "y") +  
        scale_y_discrete(position = "right") +
        scale_x_continuous(expand = expansion(mult = c(0.05, 0)), breaks = c(-0.5, 0, 0.5, 1), labels = c("-0.5", "0", "0.5", "1")) +
        labs(x = "Standardised Mean Difference", y = NULL) +
        scale_color_manual(values = colors) +
        scale_fill_manual(values = colors) +
        guides(
          color = guide_legend(title = "Data source"),
          fill  = guide_legend(title = "Data source")
        ) +
        theme_bw() + 
        theme(
          panel.grid.major.y = element_line(color = "grey90", size = 0.5), 
          panel.grid.minor.y = element_blank(),
          panel.grid.major.x = element_blank(),
          panel.grid.minor.x = element_blank(),
          strip.text = element_text(face = "bold", size = 10),
          strip.placement = "outside", 
          legend.position = "bottom",
          legend.title = element_text(face = "bold"),
          axis.text.y = element_text(face = "bold", size = 9),
          panel.spacing.x = unit(0.5, "lines"),
          panel.spacing.y = unit(0.8, "lines")
        )
    )
    
         cat("\n\n\\pagebreak\n")
        
  }
}
```