# Generated by OmopViewer 0.4.0
# Be careful editing this file

server <- function(input, output, session) {
  # download raw data -----
  output$download_raw <- shiny::downloadHandler(
    filename = "results.csv",
    content = function(file) {
      data |>
        omopgenerics::bind() |>
        omopgenerics::exportSummarisedResult(fileName = file)
    }
  )
  # update buttons ----
  updateButtons <- shiny::reactiveValues(
    summarise_omop_snapshot = FALSE,
    summarise_cohort_count = FALSE,
    summarise_cohort_attrition = FALSE,
    summarise_characteristics = FALSE,
    summarise_large_scale_characteristics = FALSE,
    incidence_rate_ratio = FALSE,
    propensity_score_coeficcients = FALSE,
    propensity_scores = FALSE,
    summarise_sampling = FALSE,
    summarise_standardised_mean_differences = FALSE,
    cohort_exit = FALSE,
    gestational_time_distributions = FALSE,
    negative_control_outcomes = FALSE
  )
  
  # summarise_omop_snapshot -----
  getSummariseOmopSnapshotTable <- shiny::reactive({
    data[["summarise_omop_snapshot"]] |>
      OmopSketch::tableOmopSnapshot()
  })
  output$summarise_omop_snapshot_table <- gt::render_gt({
    getSummariseOmopSnapshotTable()
  })
  output$summarise_omop_snapshot_table_download <- shiny::downloadHandler(
    filename = paste0("table_snapshot.", input$summarise_omop_snapshot_table_format),
    content = function(file) {
      gt::gtsave(getSummariseOmopSnapshotTable(), file)
    }
  )
  # summarise_cohort_count -----
  ## update message if filter is changed
  shiny::observeEvent(input$summarise_cohort_count_cdm_name,
                      {
                        updateButtons$summarise_cohort_count <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_cohort_count_cohort_name,
                      {
                        updateButtons$summarise_cohort_count <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_cohort_count_variable_name,
                      {
                        updateButtons$summarise_cohort_count <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_cohort_count_table_name,
                      {
                        updateButtons$summarise_cohort_count <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_cohort_count_weighting,
                      {
                        updateButtons$summarise_cohort_count <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$summarise_cohort_count, {
    if (updateButtons$summarise_cohort_count == TRUE) {
      output$update_message_summarise_cohort_count <- shiny::renderText("Filters have changed please consider to use the update content button!")
    } else {
      output$update_message_summarise_cohort_count <- shiny::renderText("")
    }
  })
  shiny::observeEvent(input$update_summarise_cohort_count, {
    updateButtons$summarise_cohort_count <- FALSE
  })
  
  ## get summarise_cohort_count data
  getSummariseCohortCountData <- shiny::eventReactive(input$update_summarise_cohort_count, {
    x <- data[["summarise_cohort_count"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_cohort_count_cdm_name,
        .data$variable_name %in% input$summarise_cohort_count_variable_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_cohort_count_cohort_name) |>
      omopgenerics::filterSettings(
        .data$table_name %in% input$summarise_cohort_count_table_name
      ) |>
      dplyr::group_by(group_level) |>
      dplyr::filter(result_id == min(result_id)) |>
      dplyr::ungroup() |> 
      omopgenerics::newSummarisedResult(settings = omopgenerics::settings(data$summarise_cohort_count))
  })
  getSummariseCohortCountTable <- shiny::reactive({
    getSummariseCohortCountData() |>
      CohortCharacteristics::tableCohortCount(
        header = input$summarise_cohort_count_table_header,
        groupColumn = input$summarise_cohort_count_table_group_column,
        hide = input$summarise_cohort_count_table_hide
      )
  })
  output$summarise_cohort_count_table <- gt::render_gt({
    getSummariseCohortCountTable()
  })
  output$summarise_cohort_count_table_download <- shiny::downloadHandler(
    filename = paste0("table_count.", input$summarise_cohort_count_table_format),
    content = function(file) {
      gt::gtsave(getSummariseCohortCountTable(), file)
    }
  )
  getSummariseCohortCountPlot <- shiny::reactive({
    getSummariseCohortCountData() |>
      CohortCharacteristics::plotCohortCount(
        facet = input$summarise_cohort_count_plot_facet,
        colour = input$summarise_cohort_count_plot_colour
      )
  })
  output$summarise_cohort_count_plot <- shiny::renderUI({
    x <- getSummariseCohortCountPlot()
    renderInteractivePlot(x, input$summarise_cohort_count_plot_interactive)
  })
  output$summarise_cohort_count_plot_download <- shiny::downloadHandler(
    filename = "plot_count.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseCohortCountPlot(),
        width = as.numeric(input$summarise_cohort_count_plot_width),
        height = as.numeric(input$summarise_cohort_count_plot_height),
        units = input$summarise_cohort_count_plot_units,
        dpi = as.numeric(input$summarise_cohort_count_plot_dpi)
      )
    }
  )
  # summarise_cohort_attrition -----
  ## update message if filter is changed
  shiny::observeEvent(input$summarise_cohort_attrition_cdm_name,
                      {
                        updateButtons$summarise_cohort_attrition <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_cohort_attrition_cohort_name,
                      {
                        updateButtons$summarise_cohort_attrition <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_cohort_attrition_variable_name,
                      {
                        updateButtons$summarise_cohort_attrition <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$summarise_cohort_attrition, {
    if (updateButtons$summarise_cohort_attrition == TRUE) {
      output$update_message_summarise_cohort_attrition <- shiny::renderText("Filters have changed please consider to use the update content button!")
    } else {
      output$update_message_summarise_cohort_attrition <- shiny::renderText("")
    }
  })
  shiny::observeEvent(input$update_summarise_cohort_attrition, {
    updateButtons$summarise_cohort_attrition <- FALSE
  })
  
  ## get summarise_cohort_attrition data
  getSummariseCohortAttritionData <- shiny::eventReactive(input$update_summarise_cohort_attrition, {
    data[["summarise_cohort_attrition"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_cohort_attrition_cdm_name,
        .data$variable_name %in% input$summarise_cohort_attrition_variable_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_cohort_attrition_cohort_name)
  })
  getSummariseCohortAttritionTable <- shiny::reactive({
    getSummariseCohortAttritionData() |>
      CohortCharacteristics::tableCohortAttrition(
        header = input$summarise_cohort_attrition_table_header,
        groupColumn = input$summarise_cohort_attrition_table_group_column,
        hide = input$summarise_cohort_attrition_table_hide
      )
  })
  output$summarise_cohort_attrition_table <- gt::render_gt({
    getSummariseCohortAttritionTable()
  })
  output$summarise_cohort_attrition_table_download <- shiny::downloadHandler(
    filename = paste0("table_attrition.", input$summarise_cohort_attrition_table_format),
    content = function(file) {
      gt::gtsave(getSummariseCohortAttritionTable(), file)
    }
  )
  getSummariseCohortAttritionDiagram <- shiny::reactive({
    getSummariseCohortAttritionData() |>
      CohortCharacteristics::plotCohortAttrition(
        show = input$summarise_cohort_attrition_diagram_show
      )
  })
  output$summarise_cohort_attrition_diagram <- DiagrammeR::renderGrViz({
    getSummariseCohortAttritionDiagram()
  })
  output$summarise_cohort_attrition_diagram_download <- shiny::downloadHandler(
    filename = "attrition_diagram.png",
    content = function(file) {
      svg <- DiagrammeRsvg::export_svg(getSummariseCohortAttritionDiagram())
      rsvg::rsvg_png(charToRaw(svg), file, width = input$summarise_cohort_attrition_diagram_width)
    }
  )
  # summarise_characteristics -----
  ## update message if filter is changed
  shiny::observeEvent(input$summarise_characteristics_cdm_name,
                      {
                        updateButtons$summarise_characteristics <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_characteristics_cohort_name,
                      {
                        updateButtons$summarise_characteristics <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_characteristics_exposure,
                      {
                        updateButtons$summarise_characteristics <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_characteristics_vaccine_brand,
                      {
                        updateButtons$summarise_characteristics <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_characteristics_gestational_trimester,
                      {
                        updateButtons$summarise_characteristics <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_characteristics_age_group,
                      {
                        updateButtons$summarise_characteristics <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_characteristics_variable_name,
                      {
                        updateButtons$summarise_characteristics <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_characteristics_estimate_name,
                      {
                        updateButtons$summarise_characteristics <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$summarise_characteristics, {
    if (updateButtons$summarise_characteristics == TRUE) {
      output$update_message_summarise_characteristics <- shiny::renderText("Filters have changed please consider to use the update content button!")
    } else {
      output$update_message_summarise_characteristics <- shiny::renderText("")
    }
  })
  shiny::observeEvent(input$update_summarise_characteristics, {
    updateButtons$summarise_characteristics <- FALSE
  })
  
  ## get summarise_characteristics data
  getSummariseCharacteristicsData <- shiny::eventReactive(input$update_summarise_characteristics, {
    data[["summarise_characteristics"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_characteristics_cdm_name,
        .data$variable_name %in% input$summarise_characteristics_variable_name,
        .data$estimate_name %in% input$summarise_characteristics_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_characteristics_cohort_name) |>
      omopgenerics::filterStrata(
        .data$exposure %in% input$summarise_characteristics_exposure,
        .data$vaccine_brand %in% input$summarise_characteristics_vaccine_brand,
        .data$gestational_trimester %in% input$summarise_characteristics_gestational_trimester,
        .data$age_group %in% input$summarise_characteristics_age_group
      ) |>
      filterSettings(.data$weighting %in% input$summarise_characteristics_weighting)
  })
  getSummariseCharacteristicsTidy <- shiny::reactive({
    tidyDT(getSummariseCharacteristicsData(), input$summarise_characteristics_tidy_columns, input$summarise_characteristics_tidy_pivot_estimates)
  })
  output$summarise_characteristics_tidy <- DT::renderDT({
    getSummariseCharacteristicsTidy()
  })
  output$summarise_characteristics_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getSummariseCharacteristicsData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getSummariseCharacteristicsTable <- shiny::reactive({
    getSummariseCharacteristicsData() |>
      CohortCharacteristics::tableCharacteristics(
        header = input$summarise_characteristics_table_header,
        groupColumn = input$summarise_characteristics_table_group_column,
        hide = input$summarise_characteristics_table_hide
      )
  })
  output$summarise_characteristics_table <- gt::render_gt({
    getSummariseCharacteristicsTable()
  })
  output$summarise_characteristics_table_download <- shiny::downloadHandler(
    filename = paste0("table_characteristics.", input$summarise_characteristics_table_format),
    content = function(file) {
      gt::gtsave(getSummariseCharacteristicsTable(), file)
    }
  )
  getSummariseCharacteristicsPlot <- shiny::reactive({
    getSummariseCharacteristicsData() |>
      CohortCharacteristics::plotCharacteristics(
        plotType = input$summarise_characteristics_plot_plot_type,
        facet = input$summarise_characteristics_plot_facet,
        colour = input$summarise_characteristics_plot_colour
      )
  })
  output$summarise_characteristics_plot <- shiny::renderUI({
    x <- getSummariseCharacteristicsPlot()
    renderInteractivePlot(x, input$summarise_characteristics_plot_interactive)
  })
  output$summarise_characteristics_plot_download <- shiny::downloadHandler(
    filename = "plot_characteristics.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseCharacteristicsPlot(),
        width = as.numeric(input$summarise_characteristics_plot_width),
        height = as.numeric(input$summarise_characteristics_plot_height),
        units = input$summarise_characteristics_plot_units,
        dpi = as.numeric(input$summarise_characteristics_plot_dpi)
      )
    }
  )
  # summarise_large_scale_characteristics -----
  ## update message if filter is changed
  shiny::observeEvent(input$summarise_large_scale_characteristics_cdm_name,
                      {
                        updateButtons$summarise_large_scale_characteristics <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_large_scale_characteristics_cohort_name,
                      {
                        updateButtons$summarise_large_scale_characteristics <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_large_scale_characteristics_exposure,
                      {
                        updateButtons$summarise_large_scale_characteristics <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_large_scale_characteristics_vaccine_brand,
                      {
                        updateButtons$summarise_large_scale_characteristics <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_large_scale_characteristics_gestational_trimester,
                      {
                        updateButtons$summarise_large_scale_characteristics <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_large_scale_characteristics_age_group,
                      {
                        updateButtons$summarise_large_scale_characteristics <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_large_scale_characteristics_variable_level,
                      {
                        updateButtons$summarise_large_scale_characteristics <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_large_scale_characteristics_analysis,
                      {
                        updateButtons$summarise_large_scale_characteristics <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_large_scale_characteristics_type,
                      {
                        updateButtons$summarise_large_scale_characteristics <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_large_scale_characteristics_weighting,
                      {
                        updateButtons$summarise_large_scale_characteristics <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$summarise_large_scale_characteristics, {
    if (updateButtons$summarise_large_scale_characteristics == TRUE) {
      output$update_message_summarise_large_scale_characteristics <- shiny::renderText("Filters have changed please consider to use the update content button!")
    } else {
      output$update_message_summarise_large_scale_characteristics <- shiny::renderText("")
    }
  })
  shiny::observeEvent(input$update_summarise_large_scale_characteristics, {
    updateButtons$summarise_large_scale_characteristics <- FALSE
  })
  
  ## get summarise_large_scale_characteristics data
  getSummariseLargeScaleCharacteristicsData <- shiny::eventReactive(input$update_summarise_large_scale_characteristics, {
    data[["summarise_large_scale_characteristics"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_large_scale_characteristics_cdm_name,
        .data$variable_level %in% input$summarise_large_scale_characteristics_variable_level
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_large_scale_characteristics_cohort_name) |>
      omopgenerics::filterStrata(
        .data$exposure %in% input$summarise_large_scale_characteristics_exposure,
        .data$vaccine_brand %in% input$summarise_large_scale_characteristics_vaccine_brand,
        .data$gestational_trimester %in% input$summarise_large_scale_characteristics_gestational_trimester,
        .data$age_group %in% input$summarise_large_scale_characteristics_age_group
      ) |>
      omopgenerics::filterSettings(
        .data$weighting %in% input$summarise_large_scale_characteristics_weighting
      )
  })
  getSummariseLargeScaleCharacteristicsTableLsc <- shiny::reactive({
    # if (identical(input$summarise_large_scale_characteristics_table_lsc_compare_by, "no compare")) {
    #   cb <- NULL
    # } else {
    #   cb <- input$summarise_large_scale_characteristics_table_lsc_compare_by
    # }
    # if (identical(input$summarise_large_scale_characteristics_table_lsc_smd_reference, "no SMD")) {
    #   sr <- NULL
    # } else {
    #   sr <- input$summarise_large_scale_characteristics_table_lsc_smd_reference
    # }
    getSummariseLargeScaleCharacteristicsData() |>
      CohortCharacteristics::tableLargeScaleCharacteristics(
        compareBy = "exposure",
        hide = input$summarise_large_scale_characteristics_table_lsc_hide,
        smdReference = "comparator"
      ) 
  })
  output$summarise_large_scale_characteristics_table_lsc <- reactable::renderReactable({
    getSummariseLargeScaleCharacteristicsTableLsc()
  })
  # shiny::observeEvent(input$summarise_large_scale_characteristics_table_lsc_compare_by, {
  #   opts <- values[[paste0("summarise_large_scale_characteristics_", input$summarise_large_scale_characteristics_table_lsc_compare_by)]]
  #   opts <- c("no SMD", opts)
  #   shinyWidgets::updatePickerInput(
  #     inputId = "summarise_large_scale_characteristics_table_lsc_smd_reference",
  #     choices = opts,
  #     selected = "no SMD"
  #   )
  # })
  output$summarise_large_scale_characteristics_table_lsc_download <- shiny::downloadHandler(
    filename = "smd_results.csv",
    content = function(file) {
      rt <- getSummariseLargeScaleCharacteristicsTableLsc()
      rt$x$tag$attribs$data |>
        unclass() |>
        jsonlite::fromJSON() |>
        dplyr::as_tibble() |>
        readr::write_csv(file)
    }
  )
  getSummariseLargeScaleCharacteristicsPlotCompared <- shiny::reactive({
    res <- getSummariseLargeScaleCharacteristicsData() |>
      dplyr::mutate(
        additional_level = dplyr::if_else(additional_name == "overall", "-", additional_level),
        additional_name = dplyr::if_else(additional_name == "overall", "concept_id", additional_name)
      ) 
    res <- res |>
      omopgenerics::newSummarisedResult(settings = omopgenerics::settings(res) |> dplyr::mutate(additional = "concept_id"))
    res |>
      CohortCharacteristics::plotComparedLargeScaleCharacteristics(
        colour = "exposure",
        reference = "comparator",
        facet = input$summarise_large_scale_characteristics_plot_compared_facet,
        missings = NULL
      ) + 
      theme(legend.position="none")
  })
  output$summarise_large_scale_characteristics_plot_compared <- plotly::renderPlotly({
    getSummariseLargeScaleCharacteristicsPlotCompared()
  })
  shiny::observeEvent(input$summarise_large_scale_characteristics_plot_compared_colour, {
    opts <- values[[paste0("summarise_large_scale_characteristics_", input$summarise_large_scale_characteristics_plot_compared_colour)]]
    shinyWidgets::updatePickerInput(
      inputId = "summarise_large_scale_characteristics_plot_compared_reference",
      choices = opts,
      selected = opts[1]
    )
  })
  # incidence_rate_ratio -----
  ## update message if filter is changed
  shiny::observeEvent(input$incidence_rate_ratio_cdm_name,
                      {
                        updateButtons$incidence_rate_ratio <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$incidence_rate_ratio_cohort_name,
                      {
                        updateButtons$incidence_rate_ratio <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$incidence_rate_ratio_vaccine_brand,
                      {
                        updateButtons$incidence_rate_ratio <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$incidence_rate_ratio_gestational_trimester,
                      {
                        updateButtons$incidence_rate_ratio <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$incidence_rate_ratio_age_group,
                      {
                        updateButtons$incidence_rate_ratio <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$incidence_rate_ratio_outcome_name,
                      {
                        updateButtons$incidence_rate_ratio <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$incidence_rate_ratio_follow_up_end,
                      {
                        updateButtons$incidence_rate_ratio <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$incidence_rate_ratio_variable_name,
                      {
                        updateButtons$incidence_rate_ratio <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$incidence_rate_ratio_estimate_name,
                      {
                        updateButtons$incidence_rate_ratio <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$incidence_rate_ratio_outcome_group,
                      {
                        updateButtons$incidence_rate_ratio <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$incidence_rate_ratio_weighting,
                      {
                        updateButtons$incidence_rate_ratio <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$incidence_rate_ratio, {
    if (updateButtons$incidence_rate_ratio == TRUE) {
      output$update_message_incidence_rate_ratio <- shiny::renderText("Filters have changed please consider to use the update content button!")
    } else {
      output$update_message_incidence_rate_ratio <- shiny::renderText("")
    }
  })
  shiny::observeEvent(input$update_incidence_rate_ratio, {
    updateButtons$incidence_rate_ratio <- FALSE
  })
  
  ## get incidence_rate_ratio data
  getIncidenceRateRatioData <- shiny::eventReactive(input$update_incidence_rate_ratio, {
    data[["incidence_rate_ratio"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$incidence_rate_ratio_cdm_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$incidence_rate_ratio_cohort_name) |>
      omopgenerics::filterStrata(
        .data$vaccine_brand %in% input$incidence_rate_ratio_vaccine_brand,
        .data$gestational_trimester %in% input$incidence_rate_ratio_gestational_trimester,
        .data$age_group %in% input$incidence_rate_ratio_age_group
      ) |>
      omopgenerics::filterAdditional(
        .data$outcome_name %in% input$incidence_rate_ratio_outcome_name,
        .data$follow_up_end %in% input$incidence_rate_ratio_follow_up_end
      ) |>
      omopgenerics::filterSettings(
        .data$outcome_group %in% input$incidence_rate_ratio_outcome_group,
        .data$weighting %in% input$incidence_rate_ratio_weighting
      )
  })
  getIncidenceRateRatioTidy <- shiny::reactive({
    getIncidenceRateRatioData() |>
      omopgenerics::tidy() |>
      dplyr::select(dplyr::any_of(c(input$incidence_rate_ratio_tidy_columns, "exp_coef", "lower_ci", "upper_ci", "median", "q25", "q75", "min", "max", "count"))) |>
      DT::datatable(
        filter = "top",
        rownames = FALSE,
        options = list(searching = FALSE)
      )
  })
  output$incidence_rate_ratio_tidy <- DT::renderDT({
    getIncidenceRateRatioTidy()
  })
  output$incidence_rate_ratio_tidy_download <- shiny::downloadHandler(
    filename = "tidy_IRR_results.csv",
    content = function(file) {
      getIncidenceRateRatioData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getIncidenceRateRatioTableSummary <- shiny::reactive({
    getIncidenceRateRatioData() |>
      dplyr::filter(.data$variable_name %in% c("Person-Days", "Number persons", "Number events")) |>
      dplyr::mutate(variable_name = dplyr::if_else(.data$variable_name == "Number persons", "Number subjects", .data$variable_name)) |>
      visOmopResults::visOmopTable(
        estimateName = c(
          "N" = "<count>",
          "Median [Q25 - Q75]" = "<median> [<q25> - <q75>]",
          "Range" = "<min> - <max>"
        ),
        settingsColumn = "weighting",
        header = input$incidence_rate_ratio_table_header_summary,
        groupColumn = input$incidence_rate_ratio_table_group_column_summary,
        hide = input$incidence_rate_ratio_table_hide_summary,
        columnOrder = c(
          'cdm_name', 'cohort_name', 'vaccine_brand', 'gestational_trimester', 
          'age_group', 'follow_up_end', 'outcome_name', 'variable_name', 'variable_level', 
          'follow_up_end', 'weighting', 'estimate_name', 'estimate_value'),
        .options = list(includeHeaderName = FALSE)
      )
  })
  output$incidence_rate_ratio_table_summary <- gt::render_gt({
    getIncidenceRateRatioTableSummary()
  })
  output$incidence_rate_ratio_table_download_summary <- shiny::downloadHandler(
    filename = paste0("table_IRR_summary.", input$incidence_rate_ratio_table_format_summary),
    content = function(file) {
      gt::gtsave(getIncidenceRateRatioTableSummary(), file)
    }
  )
  getIncidenceRateRatioTableIRR <- shiny::reactive({
    getIncidenceRateRatioData() |>
      dplyr::filter(.data$variable_name == "Risk estimate") |>
      visOmopResults::visOmopTable(
        estimateName = c("IRR [95% CI]" = "<exp_coef> [<lower_ci> - <upper_ci>]"),
        settingsColumn = "weighting",
        header = input$incidence_rate_ratio_table_header_irr,
        groupColumn = input$incidence_rate_ratio_table_group_column_irr,
        hide = input$incidence_rate_ratio_table_hide_irr,
        columnOrder = c(
          'cdm_name', 'cohort_name', 'vaccine_brand', 'gestational_trimester', 
          'age_group', 'follow_up_end', 'outcome_name', 'variable_name', 'variable_level', 
          'follow_up_end', 'weighting', 'estimate_name', 'estimate_value'),
        .options = list(includeHeaderName = FALSE)
      )
  })
  output$incidence_rate_ratio_table_irr <- gt::render_gt({
    getIncidenceRateRatioTableIRR()
  })
  output$incidence_rate_ratio_table_download_irr <- shiny::downloadHandler(
    filename = paste0("table.", input$incidence_rate_ratio_table_format_irr),
    content = function(file) {
      gt::gtsave(getIncidenceRateRatioTableIRR(), file)
    }
  )
  getIRRPlot <- shiny::reactive({
    getIncidenceRateRatioData() |>
      visOmopResults::scatterPlot(
        x = input$incidence_rate_ratio_plot_y,
        y = "exp_coef",
        line = FALSE,
        point = TRUE,
        ribbon = FALSE,
        ymin = "lower_ci",
        ymax = "upper_ci",
        facet = input$incidence_rate_ratio_plot_facet,
        colour = input$incidence_rate_ratio_plot_colour,
        label = character()
      ) +
      ggplot2::coord_flip() +
      visOmopResults::themeVisOmop(fontsizeRef = 11) +
      ggplot2::xlab("IRR") 
  })
  output$incidence_rate_ratio_plot <- shiny::renderPlot({
    getIRRPlot() 
  })
  output$incidence_rate_ratio_plot_download <- shiny::downloadHandler(
    filename = "plot_IRR.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getIRRPlot(),
        width = as.numeric(input$incidence_rate_ratio_plot_width),
        height = as.numeric(input$incidence_rate_ratio_plot_height),
        units = input$incidence_rate_ratio_plot_units,
        dpi = as.numeric(input$incidence_rate_ratio_plot_dpi)
      )
    }
  )
  # propensity_scores -----
  ## update message if filter is changed
  shiny::observeEvent(input$propensity_scores_cdm_name,
                      {
                        updateButtons$propensity_scores <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$propensity_scores_cohort_name,
                      {
                        updateButtons$propensity_scores <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$propensity_scores_exposure,
                      {
                        updateButtons$propensity_scores <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$propensity_scores_variable_name,
                      {
                        updateButtons$propensity_scores <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$propensity_scores_estimate_name,
                      {
                        updateButtons$propensity_scores <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$propensity_scores, {
    if (updateButtons$propensity_scores == TRUE) {
      output$update_message_propensity_scores <- shiny::renderText("Filters have changed please consider to use the update content button!")
    } else {
      output$update_message_propensity_scores <- shiny::renderText("")
    }
  })
  shiny::observeEvent(input$update_propensity_scores, {
    updateButtons$propensity_scores <- FALSE
  })
  
  ## propensity_score_coeficcients -----
  getPropensityScoreCoeficcientsTidy <- shiny::reactive({
    data[["propensity_score_coeficcients"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$propensity_scores_cdm_name,
        .data$group_level %in% input$propensity_scores_cohort_name
      ) |> 
      visOmopResults::tidy()
  })
  output$propensity_score_coeficcients_tidy <- DT::renderDT({
    getPropensityScoreCoeficcientsTidy()
  })
  output$propensity_score_coeficcients_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getPropensityScoreCoeficcientsTidy() |>
        readr::write_csv(file = file)
    }
  )
  ## propensity_scores plot ----
  getPropensityScoresData <- shiny::eventReactive(input$update_propensity_scores, {
    data[["propensity_scores"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$propensity_scores_cdm_name,
        .data$group_level %in% input$propensity_scores_cohort_name
      ) |>
      visOmopResults::tidy()
  })
  getPropensityScorePlot <- shiny::reactive({
    getPropensityScoresData() |>
      tidyr::unite(
        col = "facet", input$propensity_score_plot_facet
      ) |>
      ggplot2::ggplot(ggplot2::aes(x = propensity_score, colour = exposure, fill = exposure)) +
      ggplot2::geom_density(alpha = 0.3) +
      ggplot2::facet_wrap(facets = vars(facet), scales = "free_y")
  })
  output$propensity_score_plot <- shiny::renderUI({
    x <- getPropensityScorePlot()
    renderInteractivePlot(x, input$propensity_score_plot_interactive)
  })
  output$propensity_score_plot_download <- shiny::downloadHandler(
    filename = "plot_propensity_score.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getPropensityScorePlot(),
        width = as.numeric(input$propensity_score_plot_width),
        height = as.numeric(input$propensity_score_plot_height),
        units = input$propensity_score_plot_units,
        dpi = as.numeric(input$propensity_score_plot_dpi)
      )
    }
  )
  # sampling and population-----
  ## update message if filter is changed
  shiny::observeEvent(input$summarise_sampling_cdm_name,
                      {
                        updateButtons$summarise_sampling <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_sampling_cohort_name,
                      {
                        updateButtons$summarise_sampling <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_sampling_variable_name,
                      {
                        updateButtons$summarise_sampling <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_sampling_estimate_name,
                      {
                        updateButtons$summarise_sampling <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$summarise_sampling, {
    if (updateButtons$summarise_sampling == TRUE) {
      output$update_message_summarise_sampling <- shiny::renderText("Filters have changed please consider to use the update content button!")
    } else {
      output$update_message_summarise_sampling <- shiny::renderText("")
    }
  })
  shiny::observeEvent(input$update_summarise_sampling, {
    updateButtons$summarise_sampling <- FALSE
  })
  ## population count ----
  getSummariseCohortCountDataPop <- shiny::eventReactive(input$update_summarise_sampling, {
    data[["summarise_characteristics"]] |>
      omopgenerics::filterSettings(weighting == FALSE) |>
      dplyr::filter(variable_name %in% c("Number records", "Number subjects")) |>
      dplyr::filter(.data$cdm_name %in% input$summarise_sampling_cdm_name) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_sampling_cohort_name) |>
      omopgenerics::filterStrata(
        .data$exposure %in% input$summarise_cohort_count_exposure_pop,
        .data$vaccine_brand %in% input$summarise_cohort_count_vaccine_brand_pop,
        .data$gestational_trimester %in% input$summarise_cohort_count_gestational_trimester_pop,
        .data$age_group %in% input$summarise_cohort_count_age_group_pop
      )
  })
  getSummariseCohortCountTablePop <- shiny::reactive({
    getSummariseCohortCountDataPop() |>
      CohortCharacteristics::tableCharacteristics(
        header = input$summarise_cohort_count_table_header_pop,
        groupColumn = input$summarise_cohort_count_table_group_column_pop,
        hide = input$summarise_cohort_count_table_hide_pop
      )
  })
  output$summarise_cohort_count_table_pop <- gt::render_gt({
    getSummariseCohortCountTablePop()
  })
  output$summarise_cohort_count_table_download_pop <- shiny::downloadHandler(
    filename = paste0("table_population_count.", input$summarise_cohort_count_table_format_pop),
    content = function(file) {
      gt::gtsave(getSummariseCohortCountTablePop(), file)
    }
  )
  ## population attrition ----
  getSummariseCohortAttritionDataPop <- shiny::eventReactive(input$update_summarise_sampling, {
    data[["summarise_cohort_attrition"]] |>
      dplyr::filter(.data$cdm_name %in% input$summarise_sampling_cdm_name) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_sampling_cohort_name) |>
      omopgenerics::filterSettings(.data$table_name %in% "Study population") |>
      omopgenerics::filterSettings(.data$table_name %in% "Study population") |>
      dplyr::mutate(additional_level = as.numeric(additional_level)) |>
      dplyr::filter(additional_level < 15 | additional_level > 23) |>
      dplyr::filter(!(additional_level == 24 & group_level %in% c("population_objective_2", "population_objective_3"))) |>
      dplyr::filter(!(additional_level == 14 & group_level %in% c("population_objective_1"))) |>
      dplyr::mutate(additional_level = as.character(additional_level)) 
  })
  getSummariseCohortAttritionTablePop <- shiny::reactive({
    getSummariseCohortAttritionDataPop() |>
      dplyr::filter(.data$variable_name %in% input$summarise_cohort_attrition_variable_name_pop) |>
      CohortCharacteristics::tableCohortAttrition(
        header = input$summarise_cohort_attrition_table_header_pop,
        groupColumn = input$summarise_cohort_attrition_table_group_column_pop,
        hide = input$summarise_cohort_attrition_table_hide_pop
      )
  })
  output$summarise_cohort_attrition_table_pop <- gt::render_gt({
    getSummariseCohortAttritionTablePop()
  })
  output$summarise_cohort_attrition_table_download_pop <- shiny::downloadHandler(
    filename = paste0("table_population_attrition.", input$summarise_cohort_attrition_table_format_pop),
    content = function(file) {
      gt::gtsave(getSummariseCohortAttritionTablePop(), file)
    }
  )
  getSummariseCohortAttritionDiagramPop <- shiny::reactive({
    getSummariseCohortAttritionDataPop() |>
      dplyr::filter(.data$variable_name %in% input$summarise_cohort_attrition_variable_name_pop) |>
      CohortCharacteristics::plotCohortAttrition(
        show = input$summarise_cohort_attrition_diagram_show_pop
      )
  })
  output$summarise_cohort_attrition_diagram_pop <- DiagrammeR::renderGrViz({
    getSummariseCohortAttritionDiagramPop()
  })
  output$summarise_cohort_attrition_diagram_download_pop <- shiny::downloadHandler(
    filename = "attrition_population_diagram.png",
    content = function(file) {
      svg <- DiagrammeRsvg::export_svg(getSummariseCohortAttritionDiagramPop())
      rsvg::rsvg_png(charToRaw(svg), file, width = input$summarise_cohort_attrition_diagram_width_pop)
    }
  )
  ## summarise_sampling ----
  getSummariseSamplingData <- shiny::eventReactive(input$update_summarise_sampling, {
    data[["summarise_sampling"]] |>
      dplyr::filter(.data$cdm_name %in% input$summarise_sampling_cdm_name) |>
      omopgenerics::filterGroup(.data$cohort_name %in% paste0("source_", input$summarise_sampling_cohort_name))
  })
  getSummariseSamplingTable <- shiny::reactive({
    getSummariseSamplingData() |>
      visOmopResults::visOmopTable(
        estimateName = c(
          "N" = "<count>",
          "Median [Q25 - Q75]" = "<median> [<q25> - <q75>]",
          "Range" = "<min> - <max>"
        ),
        header = input$summarise_sampling_table_header, 
        groupColumn = input$summarise_sampling_table_group_column,
        hide = input$summarise_sampling_table_hide
      )
  })
  output$summarise_sampling_table <- gt::render_gt({
    getSummariseSamplingTable()
  })
  output$summarise_sampling_table_download <- shiny::downloadHandler(
    filename = paste0("table.", input$summarise_sampling_table_format),
    content = function(file) {
      gt::gtsave(getSummariseSamplingTable(), file)
    }
  )
  # cohort_exit -----
  ## update message if filter is changed
  shiny::observeEvent(input$cohort_exit_cdm_name,
                      {
                        updateButtons$cohort_exit <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$cohort_exit_cohort_name,
                      {
                        updateButtons$cohort_exit <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$cohort_exit_exposure,
                      {
                        updateButtons$cohort_exit <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$cohort_exit_vaccine_brand,
                      {
                        updateButtons$cohort_exit <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$cohort_exit_gestational_trimester,
                      {
                        updateButtons$cohort_exit <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$cohort_exit_age_group,
                      {
                        updateButtons$cohort_exit <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$cohort_exit_exit_reason,
                      {
                        updateButtons$cohort_exit <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$cohort_exit_analysis,
                      {
                        updateButtons$cohort_exit <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$cohort_exit_variable_name,
                      {
                        updateButtons$cohort_exit <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$cohort_exit_estimate_name,
                      {
                        updateButtons$cohort_exit <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$cohort_exit_weighting,
                      {
                        updateButtons$cohort_exit <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$cohort_exit, {
    if (updateButtons$cohort_exit == TRUE) {
      output$update_message_cohort_exit <- shiny::renderText("Filters have changed please consider to use the update content button!")
    } else {
      output$update_message_cohort_exit <- shiny::renderText("")
    }
  })
  shiny::observeEvent(input$update_cohort_exit, {
    updateButtons$cohort_exit <- FALSE
  })
  
  ## get cohort_exit data
  getCohortExitData <- shiny::eventReactive(input$update_cohort_exit, {
    data[["cohort_exit"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$cohort_exit_cdm_name,
        .data$variable_name %in% input$cohort_exit_variable_name,
        .data$estimate_name %in% input$cohort_exit_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$cohort_exit_cohort_name) |>
      omopgenerics::filterStrata(
        .data$exposure %in% input$cohort_exit_exposure,
        .data$vaccine_brand %in% input$cohort_exit_vaccine_brand,
        .data$gestational_trimester %in% input$cohort_exit_gestational_trimester,
        .data$age_group %in% input$cohort_exit_age_group
      ) |>
      omopgenerics::filterAdditional(
        .data$exit_reason %in% input$cohort_exit_exit_reason,
        .data$analysis %in% input$cohort_exit_analysis
      ) |>
      omopgenerics::filterSettings(.data$weighting %in% input$cohort_exit_weighting) 
  })
  getCohortExitTable <- shiny::reactive({
    getCohortExitData() |>
      visOmopResults::visOmopTable(
        estimateName = c(
          "N (%)" = "<count> (<percentage>%)",
          "N" = "<count>",
          "Median [Q25 - Q75]" = "<median> [<q25> - <q75>]",
          "Range" = "<min> - <max>"
        ),
        header = input$cohort_exit_table_header,
        groupColumn = input$cohort_exit_table_group_column,
        hide = input$cohort_exit_table_hide,
        columnOrder =  c(
          'cdm_name', 'cohort_name', 'exposure', 'vaccine_brand', 'gestational_trimester', 
          'age_group', 'exit_reason', 'variable_name', 'variable_level', 'analysis', 'weighting',
          'estimate_name'
        ),
        factor = list("exit_reason" = c("overall", "date_of_death", "next_covid_vaccine", "observation_end", "covid_infection" ))
      )
  })
  output$cohort_exit_table <- gt::render_gt({
    getCohortExitTable()
  })
  output$cohort_exit_table_download <- shiny::downloadHandler(
    filename = paste0("table_cohort_exit.", input$cohort_exit_table_format),
    content = function(file) {
      gt::gtsave(getCohortExitTable(), file)
    }
  )
  # gestational_time_distributions -----
  ## update message if filter is changed
  shiny::observeEvent(input$gestational_time_distributions_cdm_name,
                      {
                        updateButtons$gestational_time_distributions <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$gestational_time_distributions_cohort_name,
                      {
                        updateButtons$gestational_time_distributions <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$gestational_time_distributions_exposure,
                      {
                        updateButtons$gestational_time_distributions <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$gestational_time_distributions_vaccine_brand,
                      {
                        updateButtons$gestational_time_distributions <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$gestational_time_distributions_gestational_trimester,
                      {
                        updateButtons$gestational_time_distributions <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$gestational_time_distributions_age_group,
                      {
                        updateButtons$gestational_time_distributions <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$gestational_time_distributions_variable_name,
                      {
                        updateButtons$gestational_time_distributions <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$gestational_time_distributions_estimate_name,
                      {
                        updateButtons$gestational_time_distributions <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$gestational_time_distributions_weighting,
                      {
                        updateButtons$gestational_time_distributions <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$gestational_time_distributions, {
    if (updateButtons$gestational_time_distributions == TRUE) {
      output$update_message_gestational_time_distributions <- shiny::renderText("Filters have changed please consider to use the update content button!")
    } else {
      output$update_message_gestational_time_distributions <- shiny::renderText("")
    }
  })
  shiny::observeEvent(input$update_gestational_time_distributions, {
    updateButtons$gestational_time_distributions <- FALSE
  })
  
  ## get gestational_time_distributions data
  getGestationalTimeDistributionsData <- shiny::eventReactive(input$update_gestational_time_distributions, {
    data[["gestational_time_distributions"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$gestational_time_distributions_cdm_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$gestational_time_distributions_cohort_name) |>
      omopgenerics::filterStrata(
        .data$exposure %in% input$gestational_time_distributions_exposure,
        .data$vaccine_brand %in% input$gestational_time_distributions_vaccine_brand,
        .data$gestational_trimester %in% input$gestational_time_distributions_gestational_trimester,
        .data$age_group %in% input$gestational_time_distributions_age_group
      ) |>
      omopgenerics::filterSettings(.data$weighting %in% input$gestational_time_distributions_weighting)
  })
  getTimeDistributionsPlot <- shiny::reactive({
    if (input$gestational_time_distributions_plot_type == "calendar_time") {
      getGestationalTimeDistributionsData() |>
        dplyr::mutate(variable_name = dplyr::if_else(.data$variable_name != "gestational_day", "calendar_week", .data$variable_name)) |>
        dplyr::filter(.data$variable_name != "gestational_day") |>
        omopgenerics::tidy() |>
        dplyr::mutate(variable_level = as.Date(variable_level)) |>
        visOmopResults::barPlot(
          x = "variable_level",
          y = "count",
          colour = input$gestational_time_distributions_plot_colour,
          facet = input$gestational_time_distributions_plot_facet
        ) +
        ggplot2::theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
        ggplot2::scale_x_date(breaks = "2 month") +
        ggplot2::xlab("")
    } else {
      getGestationalTimeDistributionsData() |>
        dplyr::mutate(variable_name = dplyr::if_else(.data$variable_name != "gestational_day", "calendar_week", .data$variable_name)) |>
        dplyr::filter(.data$variable_name == "gestational_day") |>
        omopgenerics::tidy() |>
        dplyr::mutate(
          gestational_week = as.numeric(.data$variable_level),
          variable_level = cut(x = .data$gestational_week, breaks = seq.int(0, 400, 7), labels = paste0("Week ", 0:56), right = FALSE)
        ) |>
        dplyr::select(!"gestational_week") |>
        dplyr::group_by(cdm_name, cohort_name, exposure, vaccine_brand, gestational_trimester, age_group, variable_name, weighting, variable_level) |>
        dplyr::summarise(count = sum(count), .groups = "drop") |>
        visOmopResults::barPlot(
          x = "variable_level",
          y = "count",
          colour = input$gestational_time_distributions_plot_colour,
          facet = input$gestational_time_distributions_plot_facet
        ) +
        ggplot2::theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) 
    }
  })
  output$gestational_time_distributions_plot <- shiny::renderPlot({
    getTimeDistributionsPlot()
  })
  output$gestational_time_distributions_plot_download <- shiny::downloadHandler(
    filename = "plot_time_distributions.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getTimeDistributionsPlot(),
        width = as.numeric(input$gestational_time_distributions_plot_width),
        height = as.numeric(input$gestational_time_distributions_plot_height),
        units = input$gestational_time_distributions_plot_units,
        dpi = as.numeric(input$gestational_time_distributions_plot_dpi)
      )
    }
  )
  
  # negative_control_outcomes -----
  ## update message if filter is changed
  shiny::observeEvent(input$negative_control_outcomes_cdm_name,
                      {
                        updateButtons$negative_control_outcomes <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$negative_control_outcomes_cohort_name,
                      {
                        updateButtons$negative_control_outcomes <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$negative_control_outcomes_vaccine_brand,
                      {
                        updateButtons$negative_control_outcomes <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$negative_control_outcomes_gestational_trimester,
                      {
                        updateButtons$negative_control_outcomes <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$negative_control_outcomes_age_group,
                      {
                        updateButtons$negative_control_outcomes <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$negative_control_outcomes_outcome_name,
                      {
                        updateButtons$negative_control_outcomes <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$negative_control_outcomes_follow_up_end,
                      {
                        updateButtons$negative_control_outcomes <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$negative_control_outcomes_variable_name,
                      {
                        updateButtons$negative_control_outcomes <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$negative_control_outcomes_estimate_name,
                      {
                        updateButtons$negative_control_outcomes <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$negative_control_outcomes_outcome_group,
                      {
                        updateButtons$negative_control_outcomes <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$negative_control_outcomes_weighting,
                      {
                        updateButtons$negative_control_outcomes <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$negative_control_outcomes, {
    if (updateButtons$negative_control_outcomes == TRUE) {
      output$update_message_negative_control_outcomes <- shiny::renderText("Filters have changed please consider to use the update content button!")
    } else {
      output$update_message_negative_control_outcomes <- shiny::renderText("")
    }
  })
  shiny::observeEvent(input$update_negative_control_outcomes, {
    updateButtons$negative_control_outcomes <- FALSE
  })
  
  ## get negative_control_outcomes data
  getNegativeControlOutcomesData <- shiny::eventReactive(input$update_negative_control_outcomes, {
    data[["negative_control_outcomes"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$negative_control_outcomes_cdm_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$negative_control_outcomes_cohort_name) |>
      omopgenerics::filterStrata(
        .data$vaccine_brand %in% input$negative_control_outcomes_vaccine_brand,
        .data$gestational_trimester %in% input$negative_control_outcomes_gestational_trimester,
        .data$age_group %in% input$negative_control_outcomes_age_group
      ) |>
      omopgenerics::filterAdditional(
        .data$outcome_name %in% input$negative_control_outcomes_outcome_name,
        .data$follow_up_end %in% input$negative_control_outcomes_follow_up_end
      ) |>
      omopgenerics::filterSettings(
        .data$weighting %in% input$negative_control_outcomes_weighting
      )
  })
  getNegativeControlOutcomesTidy <- shiny::reactive({
    getNegativeControlOutcomesData() |>
      omopgenerics::tidy() |>
      dplyr::select(dplyr::any_of(c(input$negative_control_outcomes_tidy_columns, "exp_coef", "lower_ci", "upper_ci", "median", "q25", "q75", "min", "max", "count"))) |>
      DT::datatable(
        filter = "top",
        rownames = FALSE,
        options = list(searching = FALSE)
      )
  })
  output$negative_control_outcomes_tidy <- DT::renderDT({
    getNegativeControlOutcomesTidy()
  })
  output$negative_control_outcomes_tidy_download <- shiny::downloadHandler(
    filename = "tidy_nco_results.csv",
    content = function(file) {
      getNegativeControlOutcomesData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getNegativeControlOutcomesTableSummary <- shiny::reactive({
    getNegativeControlOutcomesData() |>
      dplyr::filter(.data$variable_name %in% c("Person-Days", "Number persons", "Number events")) |>
      dplyr::mutate(variable_name = dplyr::if_else(.data$variable_name == "Number persons", "Number subjects", .data$variable_name)) |>
      visOmopResults::visOmopTable(
        estimateName = c(
          "N" = "<count>",
          "Median [Q25 - Q75]" = "<median> [<q25> - <q75>]",
          "Range" = "<min> - <max>"
        ),
        settingsColumn = "weighting",
        header = input$negative_control_outcomes_table_header_summary,
        groupColumn = input$negative_control_outcomes_table_group_column_summary,
        hide = input$negative_control_outcomes_table_hide_summary,
        columnOrder = c(
          'cdm_name', 'cohort_name', 'vaccine_brand', 'gestational_trimester', 
          'age_group', 'follow_up_end', 'outcome_name', 'variable_name', 'variable_level', 
          'follow_up_end', 'weighting', 'estimate_name', 'estimate_value'),
        .options = list(includeHeaderName = FALSE)
      )
  })
  output$negative_control_outcomes_table_summary <- gt::render_gt({
    getNegativeControlOutcomesTableSummary()
  })
  output$negative_control_outcomes_table_download_summary <- shiny::downloadHandler(
    filename = paste0("table_nco_summary.", input$negative_control_outcomes_table_format_summary),
    content = function(file) {
      gt::gtsave(getNegativeControlOutcomesTableSummary(), file)
    }
  )
  getNegativeControlOutcomesTableIRR <- shiny::reactive({
    getNegativeControlOutcomesData() |>
      dplyr::filter(.data$variable_name == "Risk estimate") |>
      visOmopResults::visOmopTable(
        estimateName = c("IRR [95% CI]" = "<exp_coef> [<lower_ci> - <upper_ci>]"),
        settingsColumn = "weighting",
        header = input$negative_control_outcomes_table_header_irr,
        groupColumn = input$negative_control_outcomes_table_group_column_irr,
        hide = input$negative_control_outcomes_table_hide_irr,
        columnOrder = c(
          'cdm_name', 'cohort_name', 'vaccine_brand', 'gestational_trimester', 
          'age_group', 'follow_up_end', 'outcome_name', 'variable_name', 'variable_level', 
          'follow_up_end', 'weighting', 'estimate_name', 'estimate_value'),
        .options = list(includeHeaderName = FALSE)
      )
  })
  output$negative_control_outcomes_table_irr <- gt::render_gt({
    getNegativeControlOutcomesTableIRR()
  })
  output$negative_control_outcomes_table_download_irr <- shiny::downloadHandler(
    filename = paste0("table.", input$negative_control_outcomes_table_format_irr),
    content = function(file) {
      gt::gtsave(getNegativeControlOutcomesTableIRR(), file)
    }
  )
  getNCOPlot <- shiny::reactive({
    getNegativeControlOutcomesData() |>
      visOmopResults::scatterPlot(
        x = input$negative_control_outcomes_plot_y,
        y = "exp_coef",
        line = FALSE,
        point = TRUE,
        ribbon = FALSE,
        ymin = "lower_ci",
        ymax = "upper_ci",
        facet = input$negative_control_outcomes_plot_facet,
        colour = input$negative_control_outcomes_plot_colour,
        label = character()
      ) +
      ggplot2::coord_flip() +
      visOmopResults::themeVisOmop(fontsizeRef = 11) +
      ggplot2::xlab("IRR") 
  })
  output$negative_control_outcomes_plot <- shiny::renderPlot({
    getNCOPlot() 
  })
  output$negative_control_outcomes_plot_download <- shiny::downloadHandler(
    filename = "plot_nco.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getNCOPlot(),
        width = as.numeric(input$negative_control_outcomes_plot_width),
        height = as.numeric(input$negative_control_outcomes_plot_height),
        units = input$negative_control_outcomes_plot_units,
        dpi = as.numeric(input$negative_control_outcomes_plot_dpi)
      )
    }
  )
}
